/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-12n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--12-120-72-72-C-60-ISO10646-1
 *      Size: 12   Baseline at: 9
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */

#include "font-terminus_12n.h"

static const uint8_t PROGMEM _font_data_terminus_12n[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '#' plain bytes */
  0x48,0xfe,0x48,0xfe,0x48,
  0x00,0x01,0x00,0x01,0x00,

  /* codepoint '-' RLE/nibble */
  0x05,0x20,

  /* codepoint '.' plain bytes */
  0x80,
  0x01,

  /* codepoint '/' plain bytes */
  0x80,0x60,0x18,0x06,
  0x01,0x00,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xfc,0x22,0x12,0x0a,0xfc,
  0x00,0x01,0x01,0x01,0x00,

  /* codepoint '1' plain bytes */
  0x04,0xfe,0x00,
  0x01,0x01,0x01,

  /* codepoint '2' plain bytes */
  0x8c,0x42,0x22,0x12,0x0c,
  0x01,0x01,0x01,0x01,0x01,

  /* codepoint '3' RLE/4 */
  0x65,0x84,0x02,0x12,0xec,
  0x1d,0x00,0x01,0x00,

  /* codepoint '4' plain bytes */
  0x60,0x50,0x48,0x44,0xfe,
  0x00,0x00,0x00,0x00,0x01,

  /* codepoint '5' RLE/4 */
  0x1d,0x9e,0x12,0xe2,
  0x1d,0x00,0x01,0x00,

  /* codepoint '6' RLE/4 */
  0x1d,0xfc,0x12,0xe0,
  0x1d,0x00,0x01,0x00,

  /* codepoint '7' RLE/4 */
  0x56,0x02,0xc2,0x32,0x0e,
  0x26,0x00,0x01,0x00,

  /* codepoint '8' RLE/4 */
  0x1d,0xec,0x12,0xec,
  0x1d,0x00,0x01,0x00,

  /* codepoint '9' RLE/4 */
  0x1d,0x1c,0x22,0xfc,
  0x1d,0x00,0x01,0x00,

  /* codepoint ':' plain bytes */
  0x98,
  0x01,

  /* codepoint '<' plain bytes */
  0x20,0x50,0x88,0x04,
  0x00,0x00,0x00,0x01,

  /* codepoint '>' plain bytes */
  0x04,0x88,0x50,0x20,
  0x01,0x00,0x00,0x00,

  /* codepoint 'A' RLE/4 */
  0x1d,0xfc,0x22,0xfc,
  0x1d,0x01,0x00,0x01,

  /* codepoint 'B' RLE/nibble */
  0x31,0xfe,0x12,  0x01,0xec,
  0x14,0x01,0x00,

  /* codepoint 'C' RLE/4 */
  0x1d,0xfc,0x02,0x84,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'D' RLE/4 */
  0x59,0xfe,0x02,0x84,0x78,
  0x0b,0x01,0x00,

  /* codepoint 'E' RLE/nibble */
  0x31,0xfe,0x12,  0x01,0x02,
  0x05,0x01,

  /* codepoint 'F' RLE/nibble */
  0x31,0xfe,0x12,  0x01,0x02,
  0x41,0x01,0x00,

  /* codepoint 'G' RLE/4 */
  0x65,0xfc,0x02,0x22,0xe4,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'H' RLE/4 */
  0x1d,0xfe,0x10,0xfe,
  0x1d,0x01,0x00,0x01,

  /* codepoint 'I' plain bytes */
  0x02,0xfe,0x02,
  0x01,0x01,0x01,

  /* codepoint 'J' plain bytes */
  0xc0,0x00,0x02,0xfe,0x02,
  0x00,0x01,0x01,0x00,0x00,

  /* codepoint 'K' plain bytes */
  0xfe,0x30,0x48,0x84,0x02,
  0x01,0x00,0x00,0x00,0x01,

  /* codepoint 'L' RLE/nibble */
  0x41,0xfe,0x00,
  0x05,0x01,

  /* codepoint 'M' plain bytes */
  0xfe,0x04,0x18,0x04,0xfe,
  0x01,0x00,0x00,0x00,0x01,

  /* codepoint 'N' plain bytes */
  0xfe,0x08,0x10,0x20,0xfe,
  0x01,0x00,0x00,0x00,0x01,

  /* codepoint 'O' RLE/4 */
  0x1d,0xfc,0x02,0xfc,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'P' RLE/nibble */
  0x31,0xfe,0x22,  0x01,0x1c,
  0x41,0x01,0x00,

  /* codepoint 'Q' plain bytes */
  0xfc,0x02,0x82,0x02,0xfc,
  0x00,0x01,0x01,0x01,0x02,

  /* codepoint 'R' plain bytes */
  0xfe,0x22,0x62,0xa2,0x1c,
  0x01,0x00,0x00,0x00,0x01,

  /* codepoint 'S' RLE/4 */
  0x1d,0x8c,0x12,0xe4,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'T' RLE/4 */
  0x26,0x02,0xfe,0x02,
  0x26,0x00,0x01,0x00,

  /* codepoint 'U' RLE/4 */
  0x1d,0xfe,0x00,0xfe,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'V' plain bytes */
  0x0e,0x70,0x80,0x70,0x0e,
  0x00,0x00,0x01,0x00,0x00,

  /* codepoint 'W' plain bytes */
  0xfe,0x80,0x60,0x80,0xfe,
  0x01,0x00,0x00,0x00,0x01,

  /* codepoint 'X' plain bytes */
  0x86,0x48,0x30,0x48,0x86,
  0x01,0x00,0x00,0x00,0x01,

  /* codepoint 'Y' plain bytes */
  0x06,0x18,0xe0,0x18,0x06,
  0x00,0x00,0x01,0x00,0x00,

  /* codepoint 'Z' plain bytes */
  0xc2,0x22,0x12,0x0a,0x06,
  0x01,0x01,0x01,0x01,0x01,

  /* codepoint '[' RLE/nibble */
  0x21,0xfe,0x02,
  0x03,0x01,

  /* codepoint ']' RLE/nibble */
  0x12,0x02,0xfe,
  0x03,0x01,

  /* codepoint '_' RLE/nibble */
  0x05,0x02,

  /* codepoint 'a' RLE/nibble */
  0x31,0xc0,0x28,  0x01,0xf0,
  0x41,0x00,0x01,

  /* codepoint 'b' RLE/nibble */
  0x31,0xfe,0x08,  0x01,0xf0,
  0x14,0x01,0x00,

  /* codepoint 'c' RLE/4 */
  0x1d,0xf0,0x08,0x90,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'd' RLE/nibble */
  0x31,0xf0,0x08,  0x01,0xfe,
  0x41,0x00,0x01,

  /* codepoint 'e' RLE/4 */
  0x1d,0xf0,0x28,0xb0,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'f' plain bytes */
  0x08,0xfc,0x0a,0x02,
  0x00,0x01,0x00,0x00,

  /* codepoint 'g' RLE/4 */
  0x1d,0xf0,0x08,0xf8,
  0x1d,0x00,0x05,0x03,

  /* codepoint 'h' RLE/4 */
  0x1d,0xfe,0x08,0xf0,
  0x1d,0x01,0x00,0x01,

  /* codepoint 'i' plain bytes */
  0x08,0xfb,0x00,
  0x01,0x01,0x01,

  /* codepoint 'j' plain bytes */
  0x00,0x00,0x08,0xfb,
  0x02,0x04,0x04,0x03,

  /* codepoint 'k' plain bytes */
  0xfe,0x60,0x90,0x08,
  0x01,0x00,0x00,0x01,

  /* codepoint 'l' plain bytes */
  0x02,0xfe,0x00,
  0x01,0x01,0x01,

  /* codepoint 'm' plain bytes */
  0xf8,0x08,0xf8,0x08,0xf0,
  0x01,0x00,0x01,0x00,0x01,

  /* codepoint 'n' RLE/4 */
  0x1d,0xf8,0x08,0xf0,
  0x1d,0x01,0x00,0x01,

  /* codepoint 'o' RLE/4 */
  0x1d,0xf0,0x08,0xf0,
  0x1d,0x00,0x01,0x00,

  /* codepoint 'p' RLE/4 */
  0x1d,0xf8,0x08,0xf0,
  0x1d,0x07,0x01,0x00,

  /* codepoint 'q' RLE/4 */
  0x1d,0xf0,0x08,0xf8,
  0x1d,0x00,0x01,0x07,

  /* codepoint 'r' RLE/nibble */
  0x11,0xf8,0x10,  0x03,0x08,
  0x41,0x01,0x00,

  /* codepoint 's' RLE/nibble */
  0x31,0x10,0x28,  0x01,0xc8,
  0x14,0x01,0x00,

  /* codepoint 't' plain bytes */
  0x08,0xfe,0x08,0x00,
  0x00,0x00,0x01,0x01,

  /* codepoint 'u' RLE/nibble */
  0x31,0xf8,0x00,  0x01,0xf8,
  0x41,0x00,0x01,

  /* codepoint 'v' plain bytes */
  0x18,0x60,0x80,0x60,0x18,
  0x00,0x00,0x01,0x00,0x00,

  /* codepoint 'w' plain bytes */
  0xf8,0x00,0xe0,0x00,0xf8,
  0x00,0x01,0x01,0x01,0x00,

  /* codepoint 'x' plain bytes */
  0x08,0x90,0x60,0x90,0x08,
  0x01,0x00,0x00,0x00,0x01,

  /* codepoint 'y' RLE/4 */
  0x1d,0xf8,0x00,0xf8,
  0x1d,0x00,0x05,0x03,

  /* codepoint 'z' plain bytes */
  0x88,0x48,0x28,0x18,0x08,
  0x01,0x01,0x01,0x01,0x01,
};

static const struct GlyphData PROGMEM _font_glyphs_terminus_12n[] = {
  {.codepoint = ' ',    .width= 6, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '#',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width= 6, .stripe_begin=0, .stripe_end=1, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  10},
  {.codepoint = '.',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_PLAIN(0), .data_offset=  12},
  {.codepoint = '/',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  14},
  {.codepoint = '0',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  22},
  {.codepoint = '1',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  32},
  {.codepoint = '2',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  38},
  {.codepoint = '3',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  48},
  {.codepoint = '4',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  57},
  {.codepoint = '5',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  67},
  {.codepoint = '6',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  75},
  {.codepoint = '7',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  83},
  {.codepoint = '8',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  92},
  {.codepoint = '9',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 100},
  {.codepoint = ':',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 108},
  {.codepoint = '<',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 110},
  {.codepoint = '>',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 118},
  {.codepoint = 'A',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 126},
  {.codepoint = 'B',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 134},
  {.codepoint = 'C',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 142},
  {.codepoint = 'D',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 150},
  {.codepoint = 'E',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 158},
  {.codepoint = 'F',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 165},
  {.codepoint = 'G',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 173},
  {.codepoint = 'H',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 182},
  {.codepoint = 'I',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 190},
  {.codepoint = 'J',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 196},
  {.codepoint = 'K',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 206},
  {.codepoint = 'L',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 216},
  {.codepoint = 'M',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 221},
  {.codepoint = 'N',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 231},
  {.codepoint = 'O',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 241},
  {.codepoint = 'P',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 249},
  {.codepoint = 'Q',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 257},
  {.codepoint = 'R',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 267},
  {.codepoint = 'S',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 277},
  {.codepoint = 'T',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 285},
  {.codepoint = 'U',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 293},
  {.codepoint = 'V',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 301},
  {.codepoint = 'W',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 311},
  {.codepoint = 'X',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 321},
  {.codepoint = 'Y',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 331},
  {.codepoint = 'Z',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 341},
  {.codepoint = '[',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 351},
  {.codepoint = ']',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 356},
  {.codepoint = '_',    .width= 6, .stripe_begin=1, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 361},
  {.codepoint = 'a',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 363},
  {.codepoint = 'b',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 371},
  {.codepoint = 'c',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 379},
  {.codepoint = 'd',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 387},
  {.codepoint = 'e',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 395},
  {.codepoint = 'f',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 403},
  {.codepoint = 'g',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 411},
  {.codepoint = 'h',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 419},
  {.codepoint = 'i',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 427},
  {.codepoint = 'j',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 433},
  {.codepoint = 'k',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 441},
  {.codepoint = 'l',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 449},
  {.codepoint = 'm',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 455},
  {.codepoint = 'n',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 465},
  {.codepoint = 'o',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 473},
  {.codepoint = 'p',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 481},
  {.codepoint = 'q',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 489},
  {.codepoint = 'r',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 497},
  {.codepoint = 's',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 505},
  {.codepoint = 't',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 513},
  {.codepoint = 'u',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 521},
  {.codepoint = 'v',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 529},
  {.codepoint = 'w',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 539},
  {.codepoint = 'x',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 549},
  {.codepoint = 'y',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 559},
  {.codepoint = 'z',    .width= 6, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 567},
};

const struct FontData PROGMEM font_terminus_12n = {
  .available_glyphs = 73,
  .baseline = 9,
  .stripes = 2,
  .bits = _font_data_terminus_12n,
  .glyphs = _font_glyphs_terminus_12n
};
