/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-16n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--16-160-72-72-C-80-ISO10646-1
 *      Size: 16   Baseline at: 10
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */

#include "font-terminus_16n.h"

static const uint8_t PROGMEM _font_data_terminus_16n[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '#' plain bytes */
  0x48,0xff,0x48,0x48,0xff,0x48,
  0x00,0x03,0x00,0x00,0x03,0x00,

  /* codepoint '-' RLE/nibble */
  0x06,0x20,

  /* codepoint '.' plain bytes */
  0x03,

  /* codepoint '/' plain bytes */
  0x00,0xc0,0x30,0x0c,0x03,
  0x03,0x00,0x00,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xfe,0x41,0x21,0x11,0x09,0xfe,
  0x01,0x02,0x02,0x02,0x02,0x01,

  /* codepoint '1' RLE/4 */
  0x95,0x04,0x02,0xff,0x00,
  0x26,0x02,0x03,0x02,

  /* codepoint '2' plain bytes */
  0x06,0x81,0x41,0x21,0x11,0x0e,
  0x03,0x02,0x02,0x02,0x02,0x02,

  /* codepoint '3' RLE/4 */
  0x75,0x86,0x01,0x11,0xee,
  0x5d,0x01,0x02,0x02,0x01,

  /* codepoint '4' plain bytes */
  0x60,0x50,0x48,0x44,0x42,0xff,
  0x00,0x00,0x00,0x00,0x00,0x03,

  /* codepoint '5' RLE/nibble */
  0x41,0x1f,0x11,  0x01,0xe1,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint '6' RLE/4 */
  0x75,0xfc,0x12,0x11,0xe0,
  0x5d,0x01,0x02,0x02,0x01,

  /* codepoint '7' RLE/4 */
  0x56,0x01,0x81,0x61,0x19,  0x01,0x07,
  0x36,0x00,0x03,0x00,

  /* codepoint '8' RLE/nibble */
  0x41,0xee,0x11,  0x01,0xee,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint '9' RLE/4 */
  0x5d,0x1e,0x21,0x21,0xfe,
  0x5d,0x00,0x02,0x01,0x00,

  /* codepoint ':' plain bytes */
  0x18,
  0x03,

  /* codepoint '<' plain bytes */
  0x20,0x50,0x88,0x04,0x02,
  0x00,0x00,0x00,0x01,0x02,

  /* codepoint '>' plain bytes */
  0x02,0x04,0x88,0x50,0x20,
  0x02,0x01,0x00,0x00,0x00,

  /* codepoint 'A' RLE/nibble */
  0x41,0xfe,0x21,  0x01,0xfe,
  0x41,0x03,0x00,  0x01,0x03,

  /* codepoint 'B' RLE/nibble */
  0x41,0xff,0x11,  0x01,0xee,
  0x41,0x03,0x02,  0x01,0x01,

  /* codepoint 'C' RLE/nibble */
  0x41,0xfe,0x01,  0x01,0x86,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint 'D' RLE/4 */
  0x5d,0xff,0x01,0x02,0xfc,
  0x5d,0x03,0x02,0x01,0x00,

  /* codepoint 'E' RLE/nibble */
  0x31,0xff,0x11,  0x02,0x01,
  0x51,0x03,0x02,

  /* codepoint 'F' RLE/nibble */
  0x31,0xff,0x11,  0x02,0x01,
  0x51,0x03,0x00,

  /* codepoint 'G' RLE/4 */
  0x69,0xfe,0x01,0x21,0xe6,
  0x5d,0x01,0x02,0x02,0x01,

  /* codepoint 'H' RLE/nibble */
  0x41,0xff,0x10,  0x01,0xff,
  0x41,0x03,0x00,  0x01,0x03,

  /* codepoint 'I' plain bytes */
  0x01,0xff,0x01,
  0x02,0x03,0x02,

  /* codepoint 'J' plain bytes */
  0x80,0x00,0x00,0x01,0xff,0x01,
  0x01,0x02,0x02,0x02,0x01,0x00,

  /* codepoint 'K' plain bytes */
  0xff,0x30,0x48,0x84,0x02,0x01,
  0x03,0x00,0x00,0x00,0x01,0x02,

  /* codepoint 'L' RLE/nibble */
  0x51,0xff,0x00,
  0x51,0x03,0x02,

  /* codepoint 'M' plain bytes */
  0xff,0x02,0x04,0x18,0x04,0x02,0xff,
  0x03,0x00,0x00,0x00,0x00,0x00,0x03,

  /* codepoint 'N' plain bytes */
  0xff,0x08,0x10,0x20,0x40,0xff,
  0x03,0x00,0x00,0x00,0x00,0x03,

  /* codepoint 'O' RLE/nibble */
  0x41,0xfe,0x01,  0x01,0xfe,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint 'P' RLE/nibble */
  0x41,0xff,0x21,  0x01,0x1e,
  0x51,0x03,0x00,

  /* codepoint 'Q' plain bytes */
  0xfe,0x01,0x01,0x01,0x01,0xfe,
  0x01,0x02,0x02,0x03,0x02,0x05,

  /* codepoint 'R' plain bytes */
  0xff,0x21,0x61,0xa1,0x21,0x1e,
  0x03,0x00,0x00,0x00,0x01,0x02,

  /* codepoint 'S' RLE/nibble */
  0x41,0x8e,0x11,  0x01,0xe2,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint 'T' RLE/4 */
  0x37,0x01,0xff,0x01,
  0x37,0x00,0x03,0x00,

  /* codepoint 'U' RLE/nibble */
  0x41,0xff,0x00,  0x01,0xff,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint 'V' RLE/4 */
  0x65,0x1f,0xe0,0x00,0xe0,  0x01,0x1f,
  0x2a,0x00,0x03,0x00,

  /* codepoint 'W' plain bytes */
  0xff,0x00,0x80,0x60,0x80,0x00,0xff,
  0x03,0x01,0x00,0x00,0x00,0x01,0x03,

  /* codepoint 'X' plain bytes */
  0x03,0xcc,0x30,0x30,0xcc,0x03,
  0x03,0x00,0x00,0x00,0x00,0x03,

  /* codepoint 'Y' RLE/4 */
  0x55,0x03,0x0c,0x10,0xe0,  0x15,0x10,0x0c,0x03,
  0x37,0x00,0x03,0x00,

  /* codepoint 'Z' plain bytes */
  0x81,0x41,0x21,0x11,0x09,0x07,
  0x03,0x02,0x02,0x02,0x02,0x02,

  /* codepoint '[' plain bytes */
  0xff,0x01,0x01,
  0x03,0x02,0x02,

  /* codepoint ']' plain bytes */
  0x01,0x01,0xff,
  0x02,0x02,0x03,

  /* codepoint '_' RLE/nibble */
  0x06,0x08,

  /* codepoint 'a' RLE/nibble */
  0x41,0xc0,0x28,  0x01,0xf0,
  0x41,0x01,0x02,  0x01,0x03,

  /* codepoint 'b' RLE/nibble */
  0x41,0xff,0x08,  0x01,0xf0,
  0x41,0x03,0x02,  0x01,0x01,

  /* codepoint 'c' RLE/nibble */
  0x41,0xf0,0x08,  0x01,0x10,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint 'd' RLE/nibble */
  0x41,0xf0,0x08,  0x01,0xff,
  0x41,0x01,0x02,  0x01,0x03,

  /* codepoint 'e' RLE/nibble */
  0x41,0xf0,0x48,  0x01,0x70,
  0x41,0x01,0x02,  0x01,0x00,

  /* codepoint 'f' RLE/4 */
  0x66,0x08,0xfe,0x09,0x01,
  0x36,0x00,0x03,0x00,

  /* codepoint 'g' RLE/nibble */
  0x41,0xf0,0x08,  0x01,0xf8,
  0x41,0x01,0x12,  0x01,0x0f,

  /* codepoint 'h' RLE/nibble */
  0x41,0xff,0x08,  0x01,0xf0,
  0x41,0x03,0x00,  0x01,0x03,

  /* codepoint 'i' plain bytes */
  0x08,0xfb,0x00,
  0x02,0x03,0x02,

  /* codepoint 'j' RLE/4 */
  0x17,0x00,0x08,0xfb,
  0x1d,0x0c,0x10,0x0f,

  /* codepoint 'k' plain bytes */
  0xff,0x40,0x40,0xa0,0x10,0x08,
  0x03,0x00,0x00,0x00,0x01,0x02,

  /* codepoint 'l' plain bytes */
  0x01,0xff,0x00,
  0x02,0x03,0x02,

  /* codepoint 'm' plain bytes */
  0xf8,0x08,0x08,0xf8,0x08,0x08,0xf0,
  0x03,0x00,0x00,0x03,0x00,0x00,0x03,

  /* codepoint 'n' RLE/nibble */
  0x41,0xf8,0x08,  0x01,0xf0,
  0x41,0x03,0x00,  0x01,0x03,

  /* codepoint 'o' RLE/nibble */
  0x41,0xf0,0x08,  0x01,0xf0,
  0x41,0x01,0x02,  0x01,0x01,

  /* codepoint 'p' RLE/nibble */
  0x41,0xf8,0x08,  0x01,0xf0,
  0x41,0x1f,0x02,  0x01,0x01,

  /* codepoint 'q' RLE/nibble */
  0x41,0xf0,0x08,  0x01,0xf8,
  0x41,0x01,0x02,  0x01,0x1f,

  /* codepoint 'r' RLE/nibble */
  0x11,0xf8,0x10,  0x04,0x08,
  0x51,0x03,0x00,

  /* codepoint 's' RLE/nibble */
  0x41,0x30,0x48,  0x01,0x88,
  0x15,0x02,0x01,

  /* codepoint 't' RLE/4 */
  0x66,0x08,0xff,0x08,0x00,
  0x36,0x00,0x01,0x02,

  /* codepoint 'u' RLE/nibble */
  0x41,0xf8,0x00,  0x01,0xf8,
  0x41,0x01,0x02,  0x01,0x03,

  /* codepoint 'v' RLE/4 */
  0x65,0x38,0xc0,0x00,0xc0,  0x01,0x38,
  0x2a,0x00,0x03,0x00,

  /* codepoint 'w' plain bytes */
  0xf8,0x00,0x00,0xe0,0x00,0x00,0xf8,
  0x01,0x02,0x02,0x03,0x02,0x02,0x01,

  /* codepoint 'x' plain bytes */
  0x18,0xa0,0x40,0x40,0xa0,0x18,
  0x03,0x00,0x00,0x00,0x00,0x03,

  /* codepoint 'y' RLE/nibble */
  0x41,0xf8,0x00,  0x01,0xf8,
  0x41,0x01,0x12,  0x01,0x0f,

  /* codepoint 'z' plain bytes */
  0x08,0x88,0x48,0x28,0x18,0x08,
  0x03,0x02,0x02,0x02,0x02,0x02,
};

static const struct GlyphData PROGMEM _font_glyphs_terminus_16n[] = {
  {.codepoint = ' ',    .width= 8, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '#',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width= 8, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  12},
  {.codepoint = '.',    .width= 8, .stripe_begin=1, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset=  14},
  {.codepoint = '/',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  15},
  {.codepoint = '0',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  25},
  {.codepoint = '1',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  37},
  {.codepoint = '2',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  46},
  {.codepoint = '3',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  58},
  {.codepoint = '4',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  68},
  {.codepoint = '5',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  80},
  {.codepoint = '6',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  90},
  {.codepoint = '7',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 100},
  {.codepoint = '8',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 111},
  {.codepoint = '9',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 121},
  {.codepoint = ':',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 131},
  {.codepoint = '<',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 133},
  {.codepoint = '>',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 143},
  {.codepoint = 'A',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 153},
  {.codepoint = 'B',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 163},
  {.codepoint = 'C',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 173},
  {.codepoint = 'D',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 183},
  {.codepoint = 'E',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 193},
  {.codepoint = 'F',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 201},
  {.codepoint = 'G',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 209},
  {.codepoint = 'H',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 219},
  {.codepoint = 'I',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 229},
  {.codepoint = 'J',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 235},
  {.codepoint = 'K',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 247},
  {.codepoint = 'L',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 259},
  {.codepoint = 'M',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 265},
  {.codepoint = 'N',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 279},
  {.codepoint = 'O',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 291},
  {.codepoint = 'P',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 301},
  {.codepoint = 'Q',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 309},
  {.codepoint = 'R',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 321},
  {.codepoint = 'S',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 333},
  {.codepoint = 'T',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 343},
  {.codepoint = 'U',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 351},
  {.codepoint = 'V',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 361},
  {.codepoint = 'W',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 372},
  {.codepoint = 'X',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 386},
  {.codepoint = 'Y',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 398},
  {.codepoint = 'Z',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 411},
  {.codepoint = '[',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 423},
  {.codepoint = ']',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 429},
  {.codepoint = '_',    .width= 8, .stripe_begin=1, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 435},
  {.codepoint = 'a',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 437},
  {.codepoint = 'b',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 447},
  {.codepoint = 'c',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 457},
  {.codepoint = 'd',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 467},
  {.codepoint = 'e',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 477},
  {.codepoint = 'f',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 487},
  {.codepoint = 'g',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 496},
  {.codepoint = 'h',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 506},
  {.codepoint = 'i',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 516},
  {.codepoint = 'j',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 522},
  {.codepoint = 'k',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 530},
  {.codepoint = 'l',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 542},
  {.codepoint = 'm',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 548},
  {.codepoint = 'n',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 562},
  {.codepoint = 'o',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 572},
  {.codepoint = 'p',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 582},
  {.codepoint = 'q',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 592},
  {.codepoint = 'r',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 602},
  {.codepoint = 's',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 610},
  {.codepoint = 't',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 618},
  {.codepoint = 'u',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 627},
  {.codepoint = 'v',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 637},
  {.codepoint = 'w',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 648},
  {.codepoint = 'x',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 662},
  {.codepoint = 'y',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 674},
  {.codepoint = 'z',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 684},
};

const struct FontData PROGMEM font_terminus_16n = {
  .available_glyphs = 73,
  .baseline = 10,
  .stripes = 2,
  .bits = _font_data_terminus_16n,
  .glyphs = _font_glyphs_terminus_16n
};
