/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-12n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--12-120-72-72-C-60-ISO10646-1
 *      Size: 12   Baseline at: 9
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_12n_
#define FONT_terminus_12n_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_12n;

#endif /* FONT_terminus_12n_ */
