/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-16b.bdf
 *      Font: -xos4-Terminus-Bold-R-Normal--16-160-72-72-C-80-ISO10646-1
 *      Size: 16   Baseline at: 10
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */

#include "font-terminus_16b.h"

static const uint8_t PROGMEM _font_data_terminus_16b[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '#' plain bytes */
  0x48,0xff,0xff,0x48,0xff,0xff,0x48,
  0x00,0x03,0x03,0x00,0x03,0x03,0x00,

  /* codepoint '-' RLE/nibble */
  0x07,0x20,

  /* codepoint '.' plain bytes */
  0x03,0x03,

  /* codepoint '/' plain bytes */
  0x00,0xc0,0xf0,0x3c,0x0f,0x03,
  0x03,0x03,0x00,0x00,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xfe,0xff,0x61,0x31,0x19,0xff,0xfe,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint '1' RLE/4 */
  0xa5,0x04,0x06,0xff,0x00,
  0x2a,0x02,0x03,0x02,

  /* codepoint '2' RLE/4 */
  0x55,0x06,0x87,0xc1,0x61,  0x15,0x31,0x1f,0x0e,
  0x2e,0x03,0x02,0x02,

  /* codepoint '3' plain bytes */
  0x86,0x87,0x11,0x11,0x11,0xff,0xee,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint '4' RLE/nibble */
  0x11,0x60,0x70,  0x11,0x58,0x4c,  0x21,0x46,0xff,
  0x25,0x00,0x03,

  /* codepoint '5' RLE/4 */
  0x5e,0x1f,0x11,0xf1,0xe1,
  0x75,0x01,0x03,0x02,0x03,  0x01,0x01,

  /* codepoint '6' plain bytes */
  0xfc,0xfe,0x13,0x11,0x11,0xf1,0xe0,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint '7' RLE/4 */
  0x56,0x01,0x81,0xe1,0x79,  0x05,0x1f,0x07,
  0x3a,0x00,0x03,0x00,

  /* codepoint '8' plain bytes */
  0xee,0xff,0x11,0x11,0x11,0xff,0xee,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint '9' plain bytes */
  0x1e,0x3f,0x21,0x21,0x21,0xff,0xfe,
  0x00,0x02,0x02,0x02,0x03,0x01,0x00,

  /* codepoint ':' plain bytes */
  0x18,0x18,
  0x03,0x03,

  /* codepoint '<' plain bytes */
  0x20,0x70,0xd8,0x8c,0x06,0x02,
  0x00,0x00,0x00,0x01,0x03,0x02,

  /* codepoint '>' plain bytes */
  0x02,0x06,0x8c,0xd8,0x70,0x20,
  0x02,0x03,0x01,0x00,0x00,0x00,

  /* codepoint 'A' RLE/4 */
  0x75,0xfe,0xff,0x21,0xff,  0x01,0xfe,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'B' RLE/4 */
  0x5e,0xff,0x11,0xff,0xee,
  0x5e,0x03,0x02,0x03,0x01,

  /* codepoint 'C' plain bytes */
  0xfe,0xff,0x01,0x01,0x01,0x87,0x86,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint 'D' plain bytes */
  0xff,0xff,0x01,0x01,0x03,0xfe,0xfc,
  0x03,0x03,0x02,0x02,0x03,0x01,0x00,

  /* codepoint 'E' RLE/nibble */
  0x32,0xff,0x11,  0x02,0x01,
  0x52,0x03,0x02,

  /* codepoint 'F' RLE/nibble */
  0x32,0xff,0x11,  0x02,0x01,
  0x52,0x03,0x00,

  /* codepoint 'G' plain bytes */
  0xfe,0xff,0x01,0x21,0x21,0xe7,0xe6,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint 'H' RLE/4 */
  0x2e,0xff,0x10,0xff,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'I' plain bytes */
  0x01,0xff,0xff,0x01,
  0x02,0x03,0x03,0x02,

  /* codepoint 'J' plain bytes */
  0x80,0x80,0x00,0x01,0xff,0xff,0x01,
  0x01,0x03,0x02,0x02,0x03,0x01,0x00,

  /* codepoint 'K' RLE/4 */
  0x56,0xff,0x30,0x78,0xcc,  0x05,0x87,0x03,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'L' RLE/nibble */
  0x52,0xff,0x00,
  0x52,0x03,0x02,

  /* codepoint 'M' RLE/4 */
  0x55,0xff,0xfe,0x0c,0x18,  0x15,0x0c,0xfe,0xff,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'N' RLE/4 */
  0x56,0xff,0x18,0x30,0x60,  0x02,0xff,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'O' plain bytes */
  0xfe,0xff,0x01,0x01,0x01,0xff,0xfe,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint 'P' RLE/nibble */
  0x32,0xff,0x21,  0x11,0x3f,0x1e,
  0x52,0x03,0x00,

  /* codepoint 'Q' plain bytes */
  0xfe,0xff,0x01,0x01,0x01,0xff,0xfe,
  0x01,0x03,0x02,0x03,0x03,0x07,0x05,

  /* codepoint 'R' plain bytes */
  0xff,0xff,0x61,0xe1,0xa1,0x3f,0x1e,
  0x03,0x03,0x00,0x00,0x01,0x03,0x02,

  /* codepoint 'S' plain bytes */
  0x8e,0x9f,0x11,0x11,0x11,0xf3,0xe2,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint 'T' RLE/4 */
  0x3b,0x01,0xff,0x01,
  0x3b,0x00,0x03,0x00,

  /* codepoint 'U' RLE/4 */
  0x2e,0xff,0x00,0xff,
  0x75,0x01,0x03,0x02,0x03,  0x01,0x01,

  /* codepoint 'V' RLE/4 */
  0x55,0x1f,0xff,0xe0,0x00,  0x15,0xe0,0xff,0x1f,
  0x2e,0x00,0x03,0x00,

  /* codepoint 'W' plain bytes */
  0xff,0xff,0xc0,0x60,0xc0,0xff,0xff,
  0x03,0x01,0x00,0x00,0x00,0x01,0x03,

  /* codepoint 'X' RLE/4 */
  0x55,0x03,0xcf,0xfc,0x30,  0x15,0xfc,0xcf,0x03,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'Y' RLE/4 */
  0x95,0x03,0x0f,0x1c,0xf0,  0x15,0x1c,0x0f,0x03,
  0x3b,0x00,0x03,0x00,

  /* codepoint 'Z' RLE/4 */
  0x55,0x81,0xc1,0x61,0x31,  0x15,0x19,0x0f,0x07,
  0x2e,0x03,0x02,0x02,

  /* codepoint '[' RLE/nibble */
  0x22,0xff,0x01,
  0x22,0x03,0x02,

  /* codepoint ']' RLE/nibble */
  0x22,0x01,0xff,
  0x22,0x02,0x03,

  /* codepoint '_' RLE/nibble */
  0x07,0x08,

  /* codepoint 'a' RLE/4 */
  0x75,0xc0,0xe8,0x28,0xf8,  0x01,0xf0,
  0xb5,0x01,0x03,0x02,0x03,

  /* codepoint 'b' RLE/4 */
  0x5e,0xff,0x08,0xf8,0xf0,
  0x5e,0x03,0x02,0x03,0x01,

  /* codepoint 'c' plain bytes */
  0xf0,0xf8,0x08,0x08,0x08,0x18,0x10,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint 'd' RLE/4 */
  0xb5,0xf0,0xf8,0x08,0xff,
  0xb5,0x01,0x03,0x02,0x03,

  /* codepoint 'e' plain bytes */
  0xf0,0xf8,0x48,0x48,0x48,0x78,0x70,
  0x01,0x03,0x02,0x02,0x02,0x02,0x00,

  /* codepoint 'f' RLE/4 */
  0x96,0x08,0xfe,0xff,0x09,  0x01,0x01,
  0x3a,0x00,0x03,0x00,

  /* codepoint 'g' RLE/4 */
  0xb5,0xf0,0xf8,0x08,0xf8,
  0x75,0x01,0x13,0x12,0x1f,  0x01,0x0f,

  /* codepoint 'h' RLE/4 */
  0x5e,0xff,0x08,0xf8,0xf0,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'i' plain bytes */
  0x08,0xfb,0xfb,0x00,
  0x02,0x03,0x03,0x02,

  /* codepoint 'j' RLE/4 */
  0x27,0x00,0x08,0xfb,
  0x65,0x0c,0x1c,0x10,0x1f,  0x01,0x0f,

  /* codepoint 'k' plain bytes */
  0xff,0xff,0x40,0xe0,0xb0,0x18,0x08,
  0x03,0x03,0x00,0x00,0x01,0x03,0x02,

  /* codepoint 'l' plain bytes */
  0x01,0xff,0xff,0x00,
  0x02,0x03,0x03,0x02,

  /* codepoint 'm' plain bytes */
  0xf8,0xf8,0x08,0xf8,0x08,0xf8,0xf0,
  0x03,0x03,0x00,0x03,0x00,0x03,0x03,

  /* codepoint 'n' RLE/4 */
  0x5e,0xf8,0x08,0xf8,0xf0,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'o' plain bytes */
  0xf0,0xf8,0x08,0x08,0x08,0xf8,0xf0,
  0x01,0x03,0x02,0x02,0x02,0x03,0x01,

  /* codepoint 'p' RLE/4 */
  0x5e,0xf8,0x08,0xf8,0xf0,
  0x5e,0x1f,0x02,0x03,0x01,

  /* codepoint 'q' RLE/4 */
  0xb5,0xf0,0xf8,0x08,0xf8,
  0xb5,0x01,0x03,0x02,0x1f,

  /* codepoint 'r' RLE/nibble */
  0x12,0xf8,0x30,  0x31,0x18,0x08,
  0x52,0x03,0x00,

  /* codepoint 's' RLE/4 */
  0x75,0x30,0x78,0x48,0xc8,  0x01,0x88,
  0x5b,0x02,0x02,0x03,0x01,

  /* codepoint 't' RLE/4 */
  0x6a,0x08,0xff,0x08,0x00,
  0xd6,0x00,0x01,0x03,0x02,

  /* codepoint 'u' RLE/4 */
  0x2e,0xf8,0x00,0xf8,
  0xb5,0x01,0x03,0x02,0x03,

  /* codepoint 'v' RLE/4 */
  0x55,0x38,0xf8,0xc0,0x00,  0x15,0xc0,0xf8,0x38,
  0x2e,0x00,0x03,0x00,

  /* codepoint 'w' plain bytes */
  0xf8,0xf8,0x00,0xe0,0x00,0xf8,0xf8,
  0x01,0x03,0x02,0x03,0x02,0x03,0x01,

  /* codepoint 'x' RLE/4 */
  0x55,0x18,0xb8,0xe0,0x40,  0x15,0xe0,0xb8,0x18,
  0x2e,0x03,0x00,0x03,

  /* codepoint 'y' RLE/4 */
  0x2e,0xf8,0x00,0xf8,
  0x75,0x01,0x13,0x12,0x1f,  0x01,0x0f,

  /* codepoint 'z' RLE/4 */
  0x55,0x08,0x88,0xc8,0x68,  0x15,0x38,0x18,0x08,
  0x2e,0x03,0x02,0x02,
};

static const struct GlyphData PROGMEM _font_glyphs_terminus_16b[] = {
  {.codepoint = ' ',    .width= 8, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '#',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width= 8, .stripe_begin=0, .stripe_end=1, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  14},
  {.codepoint = '.',    .width= 8, .stripe_begin=1, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_PLAIN(0), .data_offset=  16},
  {.codepoint = '/',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  18},
  {.codepoint = '0',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  30},
  {.codepoint = '1',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  44},
  {.codepoint = '2',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  53},
  {.codepoint = '3',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  66},
  {.codepoint = '4',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  80},
  {.codepoint = '5',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  92},
  {.codepoint = '6',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 104},
  {.codepoint = '7',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 118},
  {.codepoint = '8',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 130},
  {.codepoint = '9',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 144},
  {.codepoint = ':',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 158},
  {.codepoint = '<',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 162},
  {.codepoint = '>',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 174},
  {.codepoint = 'A',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 186},
  {.codepoint = 'B',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 197},
  {.codepoint = 'C',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 207},
  {.codepoint = 'D',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 221},
  {.codepoint = 'E',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 235},
  {.codepoint = 'F',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 243},
  {.codepoint = 'G',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 251},
  {.codepoint = 'H',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 265},
  {.codepoint = 'I',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 273},
  {.codepoint = 'J',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 281},
  {.codepoint = 'K',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 295},
  {.codepoint = 'L',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 307},
  {.codepoint = 'M',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 313},
  {.codepoint = 'N',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 326},
  {.codepoint = 'O',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 337},
  {.codepoint = 'P',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 351},
  {.codepoint = 'Q',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 360},
  {.codepoint = 'R',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 374},
  {.codepoint = 'S',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 388},
  {.codepoint = 'T',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=0, BDFONT_RLE(2)  , .data_offset= 402},
  {.codepoint = 'U',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 410},
  {.codepoint = 'V',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 421},
  {.codepoint = 'W',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 434},
  {.codepoint = 'X',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 448},
  {.codepoint = 'Y',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=0, BDFONT_RLE(2)  , .data_offset= 461},
  {.codepoint = 'Z',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 474},
  {.codepoint = '[',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 487},
  {.codepoint = ']',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 493},
  {.codepoint = '_',    .width= 8, .stripe_begin=1, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 499},
  {.codepoint = 'a',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 501},
  {.codepoint = 'b',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 513},
  {.codepoint = 'c',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 523},
  {.codepoint = 'd',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 537},
  {.codepoint = 'e',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 547},
  {.codepoint = 'f',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 561},
  {.codepoint = 'g',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 572},
  {.codepoint = 'h',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 584},
  {.codepoint = 'i',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 593},
  {.codepoint = 'j',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 601},
  {.codepoint = 'k',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 612},
  {.codepoint = 'l',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 626},
  {.codepoint = 'm',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 634},
  {.codepoint = 'n',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 648},
  {.codepoint = 'o',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 657},
  {.codepoint = 'p',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 671},
  {.codepoint = 'q',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 681},
  {.codepoint = 'r',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 691},
  {.codepoint = 's',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 700},
  {.codepoint = 't',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 712},
  {.codepoint = 'u',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 722},
  {.codepoint = 'v',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 731},
  {.codepoint = 'w',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 744},
  {.codepoint = 'x',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 758},
  {.codepoint = 'y',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 771},
  {.codepoint = 'z',    .width= 8, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 782},
};

const struct FontData PROGMEM font_terminus_16b = {
  .available_glyphs = 73,
  .baseline = 10,
  .stripes = 2,
  .bits = _font_data_terminus_16b,
  .glyphs = _font_glyphs_terminus_16b
};
