/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-16b.bdf
 *      Font: -xos4-Terminus-Bold-R-Normal--16-160-72-72-C-80-ISO10646-1
 *      Size: 16   Baseline at: 10
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_16b_
#define FONT_terminus_16b_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_16b;

#endif /* FONT_terminus_16b_ */
