/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: knxt.bdf
 *      Font: -k-knxt-Medium-R-Normal--20-200-72-72-C-100-ISO10646-1
 *      Size: 20   Baseline at: 13
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_# 
 */

#include "font-knxt.h"

static const uint8_t PROGMEM _font_data_knxt[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '#' plain bytes */
  0x40,0x40,0xf8,0x40,0xf8,0x40,0x40,
  0x02,0x02,0x1f,0x02,0x1f,0x02,0x02,

  /* codepoint '-' RLE/nibble */
  0x07,0x01,

  /* codepoint '.' plain bytes */
  0x18,

  /* codepoint '0' plain bytes */
  0xfc,0x02,0x81,0x41,0x21,0x12,0xfc,
  0x07,0x09,0x10,0x10,0x10,0x08,0x07,

  /* codepoint '1' plain bytes */
  0x08,0x04,0x02,0xff,
  0x00,0x00,0x00,0x1f,

  /* codepoint '2' plain bytes */
  0x0c,0x02,0x01,0x01,0x81,0x42,0x3c,
  0x18,0x14,0x12,0x11,0x10,0x10,0x10,

  /* codepoint '3' plain bytes */
  0x04,0x02,0x41,0x41,0x41,0xa2,0x1c,
  0x04,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint '4' plain bytes */
  0x00,0xc0,0x30,0x0c,0x03,0xc0,0x00,
  0x07,0x04,0x04,0x04,0x04,0x1f,0x04,

  /* codepoint '5' plain bytes */
  0x3f,0x21,0x21,0x21,0x21,0x41,0x81,
  0x04,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint '6' plain bytes */
  0xf0,0x4c,0x22,0x21,0x21,0x41,0x80,
  0x07,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint '7' RLE/nibble */
  0x14,0x01,0x81,  0x11,0x71,0x0f,
  0x13,0x00,0x1c,  0x21,0x03,0x00,

  /* codepoint '8' plain bytes */
  0x1c,0xa2,0x41,0x41,0x41,0xa2,0x1c,
  0x07,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint '9' plain bytes */
  0x3c,0x42,0x81,0x81,0x81,0x42,0xfc,
  0x00,0x10,0x10,0x10,0x08,0x06,0x01,

  /* codepoint 'A' plain bytes */
  0x00,0xe0,0x1c,0x03,0x1c,0xe0,0x00,
  0x1e,0x03,0x02,0x02,0x02,0x03,0x1e,

  /* codepoint 'B' RLE/nibble */
  0x41,0xff,0x21,  0x11,0x52,0x8c,
  0x41,0x1f,0x10,  0x11,0x08,0x07,

  /* codepoint 'C' plain bytes */
  0xfc,0x02,0x01,0x01,0x01,0x02,0x04,
  0x07,0x08,0x10,0x10,0x10,0x08,0x04,

  /* codepoint 'D' RLE/nibble */
  0x41,0xff,0x01,  0x11,0x02,0xfc,
  0x41,0x1f,0x10,  0x11,0x08,0x07,

  /* codepoint 'E' RLE/nibble */
  0x41,0xff,0x41,  0x02,0x01,
  0x61,0x1f,0x10,

  /* codepoint 'F' RLE/nibble */
  0x41,0xff,0x41,  0x02,0x01,
  0x61,0x1f,0x00,

  /* codepoint 'G' plain bytes */
  0xfc,0x02,0x01,0x01,0x81,0x82,0x84,
  0x07,0x08,0x10,0x10,0x10,0x08,0x1f,

  /* codepoint 'H' RLE/nibble */
  0x51,0xff,0x40,  0x01,0xff,
  0x51,0x1f,0x00,  0x01,0x1f,

  /* codepoint 'I' plain bytes */
  0x01,0xff,0x01,
  0x10,0x1f,0x10,

  /* codepoint 'J' RLE/nibble */
  0x16,0x00,0xff,
  0x11,0x04,0x08,  0x13,0x10,0x08,  0x01,0x07,

  /* codepoint 'K' plain bytes */
  0xff,0x40,0xa0,0x10,0x08,0x04,0x03,
  0x1f,0x00,0x00,0x01,0x02,0x04,0x18,

  /* codepoint 'L' RLE/nibble */
  0x61,0xff,0x00,
  0x61,0x1f,0x10,

  /* codepoint 'M' plain bytes */
  0xff,0x0c,0x30,0xc0,0x30,0x0c,0xff,
  0x1f,0x00,0x00,0x00,0x00,0x00,0x1f,

  /* codepoint 'N' plain bytes */
  0xff,0x0c,0x30,0xc0,0x00,0x00,0xff,
  0x1f,0x00,0x00,0x00,0x03,0x0c,0x1f,

  /* codepoint 'O' plain bytes */
  0xfc,0x02,0x01,0x01,0x01,0x02,0xfc,
  0x07,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint 'P' RLE/nibble */
  0x41,0xff,0x81,  0x11,0x42,0x3c,
  0x61,0x1f,0x00,

  /* codepoint 'Q' plain bytes */
  0xfc,0x02,0x01,0x01,0x01,0x02,0xfc,
  0x07,0x08,0x10,0x10,0x14,0x08,0x17,

  /* codepoint 'R' plain bytes */
  0xff,0x81,0x81,0x81,0x81,0x42,0x3c,
  0x1f,0x00,0x00,0x00,0x01,0x06,0x18,

  /* codepoint 'S' plain bytes */
  0x1c,0x22,0x41,0x41,0x41,0x82,0x04,
  0x04,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint 'T' RLE/4 */
  0x37,0x01,0xff,0x01,
  0x37,0x00,0x1f,0x00,

  /* codepoint 'U' RLE/4 */
  0x6d,0xff,0x00,0x00,0xff,
  0x75,0x07,0x08,0x10,0x08,  0x01,0x07,

  /* codepoint 'V' plain bytes */
  0x0f,0xf0,0x00,0x00,0x00,0xf0,0x0f,
  0x00,0x00,0x07,0x18,0x07,0x00,0x00,

  /* codepoint 'W' plain bytes */
  0x1f,0xe0,0x00,0xe0,0x1f,0xe0,0x00,0xe0,0x1f,
  0x00,0x01,0x1e,0x01,0x00,0x01,0x1e,0x01,0x00,

  /* codepoint 'X' plain bytes */
  0x03,0x0c,0xb0,0x40,0xb0,0x0c,0x03,
  0x18,0x06,0x01,0x00,0x01,0x06,0x18,

  /* codepoint 'Y' RLE/4 */
  0x55,0x03,0x0c,0x30,0xc0,  0x15,0x30,0x0c,0x03,
  0x37,0x00,0x1f,0x00,

  /* codepoint 'Z' RLE/4 */
  0x56,0x01,0x81,0x41,0x21,  0x05,0x11,0x0f,
  0xb5,0x1e,0x11,0x10,0x10,

  /* codepoint '_' RLE/nibble */
  0x07,0x10,

  /* codepoint 'a' plain bytes */
  0x00,0x20,0x90,0x90,0x90,0x90,0xe0,
  0x06,0x09,0x10,0x10,0x10,0x08,0x1f,

  /* codepoint 'b' plain bytes */
  0xff,0x20,0x10,0x10,0x10,0x20,0xc0,
  0x1f,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint 'c' RLE/nibble */
  0x11,0xc0,0x20,  0x14,0x10,0x20,
  0x11,0x07,0x08,  0x14,0x10,0x08,

  /* codepoint 'd' plain bytes */
  0xc0,0x20,0x10,0x10,0x10,0x20,0xff,
  0x07,0x08,0x10,0x10,0x10,0x08,0x1f,

  /* codepoint 'e' plain bytes */
  0xc0,0x20,0x10,0x10,0x10,0x20,0xc0,
  0x07,0x09,0x11,0x11,0x11,0x11,0x09,

  /* codepoint 'f' RLE/4 */
  0x66,0x10,0xfe,0x11,0x01,
  0x36,0x00,0x1f,0x00,

  /* codepoint 'g' RLE/4 */
  0x75,0xc0,0x20,0x10,0x20,  0x01,0xf0,
  0x75,0x87,0x08,0x10,0x88,  0x01,0x7f,
  0x9d,0x00,0x01,0x01,0x00,

  /* codepoint 'h' RLE/4 */
  0x75,0xff,0x20,0x10,0x20,  0x01,0xc0,
  0x6d,0x1f,0x00,0x00,0x1f,

  /* codepoint 'i' plain bytes */
  0x10,0xf6,
  0x00,0x1f,

  /* codepoint 'j' RLE/nibble */
  0x13,0x00,0xf6,
  0x13,0x80,0x7f,

  /* codepoint 'k' plain bytes */
  0xff,0x00,0x00,0x80,0x40,0x20,0x10,
  0x1f,0x01,0x01,0x02,0x04,0x08,0x10,

  /* codepoint 'l' plain bytes */
  0x01,0xff,0x00,0x00,
  0x00,0x0f,0x10,0x10,

  /* codepoint 'm' plain bytes */
  0xf0,0x10,0x10,0xe0,0x10,0x10,0xe0,
  0x1f,0x00,0x00,0x1f,0x00,0x00,0x1f,

  /* codepoint 'n' RLE/4 */
  0x75,0xf0,0x20,0x10,0x20,  0x01,0xc0,
  0x6d,0x1f,0x00,0x00,0x1f,

  /* codepoint 'o' plain bytes */
  0xc0,0x20,0x10,0x10,0x10,0x20,0xc0,
  0x07,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint 'p' plain bytes */
  0xf0,0x20,0x10,0x10,0x10,0x20,0xc0,
  0xff,0x08,0x10,0x10,0x10,0x08,0x07,

  /* codepoint 'q' plain bytes */
  0xc0,0x20,0x10,0x10,0x10,0x20,0xf0,
  0x07,0x08,0x10,0x10,0x10,0x08,0xff,

  /* codepoint 'r' RLE/nibble */
  0x11,0xf0,0x40,  0x31,0x20,0x10,  0x01,0x20,
  0x61,0x1f,0x00,

  /* codepoint 's' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0x20,
  0x51,0x08,0x11,  0x01,0x0e,

  /* codepoint 't' RLE/4 */
  0x66,0x10,0xfc,0x10,0x00,
  0x36,0x00,0x0f,0x10,

  /* codepoint 'u' RLE/4 */
  0x6d,0xf0,0x00,0x00,0xf0,
  0x75,0x07,0x08,0x10,0x08,  0x01,0x1f,

  /* codepoint 'v' plain bytes */
  0x70,0x80,0x00,0x00,0x00,0x80,0x70,
  0x00,0x01,0x06,0x18,0x06,0x01,0x00,

  /* codepoint 'w' plain bytes */
  0xf0,0x00,0x00,0xe0,0x00,0x00,0xf0,
  0x03,0x1c,0x03,0x00,0x03,0x1c,0x03,

  /* codepoint 'x' plain bytes */
  0x30,0x40,0x80,0x00,0x80,0x40,0x30,
  0x18,0x04,0x02,0x01,0x02,0x04,0x18,

  /* codepoint 'y' plain bytes */
  0x70,0x80,0x00,0x00,0x00,0x80,0x70,
  0x80,0x81,0x66,0x18,0x06,0x01,0x00,

  /* codepoint 'z' plain bytes */
  0x10,0x10,0x10,0x10,0x90,0x50,0x30,
  0x18,0x14,0x12,0x11,0x10,0x10,0x10,
};

static const struct GlyphData PROGMEM _font_glyphs_knxt[] = {
  {.codepoint = ' ',    .width= 9, .stripe_begin=2, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '#',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width= 9, .stripe_begin=1, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  14},
  {.codepoint = '.',    .width= 9, .stripe_begin=1, .stripe_end=2, .left_margin=4, .right_margin=4, BDFONT_PLAIN(0), .data_offset=  16},
  {.codepoint = '0',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  17},
  {.codepoint = '1',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=4, BDFONT_PLAIN(0), .data_offset=  31},
  {.codepoint = '2',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  39},
  {.codepoint = '3',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  53},
  {.codepoint = '4',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  67},
  {.codepoint = '5',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  81},
  {.codepoint = '6',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  95},
  {.codepoint = '7',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 109},
  {.codepoint = '8',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 121},
  {.codepoint = '9',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 135},
  {.codepoint = 'A',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 149},
  {.codepoint = 'B',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 163},
  {.codepoint = 'C',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 175},
  {.codepoint = 'D',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 189},
  {.codepoint = 'E',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 201},
  {.codepoint = 'F',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 209},
  {.codepoint = 'G',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 217},
  {.codepoint = 'H',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 231},
  {.codepoint = 'I',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_PLAIN(0), .data_offset= 241},
  {.codepoint = 'J',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 247},
  {.codepoint = 'K',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 258},
  {.codepoint = 'L',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 272},
  {.codepoint = 'M',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 278},
  {.codepoint = 'N',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 292},
  {.codepoint = 'O',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 306},
  {.codepoint = 'P',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 320},
  {.codepoint = 'Q',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 329},
  {.codepoint = 'R',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 343},
  {.codepoint = 'S',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 357},
  {.codepoint = 'T',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 371},
  {.codepoint = 'U',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 379},
  {.codepoint = 'V',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 391},
  {.codepoint = 'W',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset= 405},
  {.codepoint = 'X',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 423},
  {.codepoint = 'Y',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 437},
  {.codepoint = 'Z',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 450},
  {.codepoint = '_',    .width= 9, .stripe_begin=1, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 463},
  {.codepoint = 'a',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 465},
  {.codepoint = 'b',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 479},
  {.codepoint = 'c',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 493},
  {.codepoint = 'd',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 505},
  {.codepoint = 'e',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 519},
  {.codepoint = 'f',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 533},
  {.codepoint = 'g',    .width= 9, .stripe_begin=0, .stripe_end=3, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 542},
  {.codepoint = 'h',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 561},
  {.codepoint = 'i',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 573},
  {.codepoint = 'j',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=4, BDFONT_RLE(1)  , .data_offset= 577},
  {.codepoint = 'k',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 583},
  {.codepoint = 'l',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 597},
  {.codepoint = 'm',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 605},
  {.codepoint = 'n',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 619},
  {.codepoint = 'o',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 631},
  {.codepoint = 'p',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 645},
  {.codepoint = 'q',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 659},
  {.codepoint = 'r',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 673},
  {.codepoint = 's',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 684},
  {.codepoint = 't',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 694},
  {.codepoint = 'u',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 703},
  {.codepoint = 'v',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 715},
  {.codepoint = 'w',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 729},
  {.codepoint = 'x',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 743},
  {.codepoint = 'y',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 757},
  {.codepoint = 'z',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 771},
};

const struct FontData PROGMEM font_knxt = {
  .available_glyphs = 67,
  .baseline = 13,
  .stripes = 3,
  .bits = _font_data_knxt,
  .glyphs = _font_glyphs_knxt
};
