/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-22n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--22-220-72-72-C-110-ISO10646-1
 *      Size: 22   Baseline at: 14
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_22n_
#define FONT_terminus_22n_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_22n;

#endif /* FONT_terminus_22n_ */
