/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-28n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--28-280-72-72-C-140-ISO10646-1
 *      Size: 28   Baseline at: 18
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_28n_
#define FONT_terminus_28n_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_28n;

#endif /* FONT_terminus_28n_ */
