/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-18n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--18-180-72-72-C-100-ISO10646-1
 *      Size: 18   Baseline at: 12
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_18n_
#define FONT_terminus_18n_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_18n;

#endif /* FONT_terminus_18n_ */
