/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-32n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--32-320-72-72-C-160-ISO10646-1
 *      Size: 32   Baseline at: 20
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_32n_
#define FONT_terminus_32n_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_32n;

#endif /* FONT_terminus_32n_ */
