/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: knxt.bdf
 *      Font: -k-knxt-Medium-R-Normal--20-200-72-72-C-100-ISO10646-1
 *      Size: 20   Baseline at: 13
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_# 
 */
#ifndef FONT_knxt_
#define FONT_knxt_

#include "bdfont-support.h"

/* font containing 67 characters */
extern const struct FontData PROGMEM font_knxt;

#endif /* FONT_knxt_ */
