/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-18n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--18-180-72-72-C-100-ISO10646-1
 *      Size: 18   Baseline at: 12
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */

#include "font-terminus_18n.h"

static const uint8_t PROGMEM _font_data_terminus_18n[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '#' plain bytes */
  0x08,0xff,0x08,0x08,0x08,0xff,0x08,
  0x01,0x0f,0x01,0x01,0x01,0x0f,0x01,

  /* codepoint '-' RLE/nibble */
  0x07,0x20,

  /* codepoint '.' plain bytes */
  0x0c,

  /* codepoint '/' plain bytes */
  0x00,0x00,0xc0,0x30,0x0c,0x03,
  0x0c,0x03,0x00,0x00,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xfe,0x81,0x41,0x21,0x11,0x09,0xfe,
  0x07,0x08,0x08,0x08,0x08,0x08,0x07,

  /* codepoint '1' RLE/4 */
  0x95,0x04,0x02,0xff,0x00,
  0x26,0x08,0x0f,0x08,

  /* codepoint '2' plain bytes */
  0x0e,0x01,0x01,0x81,0x41,0x21,0x1e,
  0x0c,0x0a,0x09,0x08,0x08,0x08,0x08,

  /* codepoint '3' RLE/nibble */
  0x11,0x06,0x01,  0x14,0x21,0xde,
  0x51,0x06,0x08,  0x01,0x07,

  /* codepoint '4' RLE/4 */
  0x55,0xc0,0x20,0x10,0x08,  0x15,0x04,0x02,0xff,
  0x1f,0x01,0x01,0x0f,

  /* codepoint '5' RLE/nibble */
  0x51,0x3f,0x21,  0x01,0xc1,
  0x51,0x06,0x08,  0x01,0x07,

  /* codepoint '6' RLE/nibble */
  0x11,0xfc,0x22,  0x14,0x21,0xc0,
  0x51,0x07,0x08,  0x01,0x07,

  /* codepoint '7' RLE/4 */
  0x5d,0x07,0x01,0xc1,0x31,  0x01,0x0f,
  0x37,0x00,0x0f,0x00,

  /* codepoint '8' RLE/nibble */
  0x51,0xde,0x21,  0x01,0xde,
  0x51,0x07,0x08,  0x01,0x07,

  /* codepoint '9' RLE/nibble */
  0x51,0x3e,0x41,  0x01,0xfe,
  0x41,0x00,0x08,  0x11,0x04,0x03,

  /* codepoint ':' plain bytes */
  0x18,
  0x06,

  /* codepoint '<' plain bytes */
  0x60,0x90,0x08,0x04,0x02,0x01,
  0x00,0x00,0x01,0x02,0x04,0x08,

  /* codepoint '>' plain bytes */
  0x01,0x02,0x04,0x08,0x90,0x60,
  0x08,0x04,0x02,0x01,0x00,0x00,

  /* codepoint 'A' RLE/nibble */
  0x51,0xfe,0x41,  0x01,0xfe,
  0x51,0x0f,0x00,  0x01,0x0f,

  /* codepoint 'B' RLE/nibble */
  0x51,0xff,0x21,  0x01,0xde,
  0x51,0x0f,0x08,  0x01,0x07,

  /* codepoint 'C' RLE/nibble */
  0x51,0xfe,0x01,  0x01,0x06,
  0x51,0x07,0x08,  0x01,0x06,

  /* codepoint 'D' RLE/nibble */
  0x41,0xff,0x01,  0x11,0x02,0xfc,
  0x41,0x0f,0x08,  0x11,0x04,0x03,

  /* codepoint 'E' RLE/nibble */
  0x41,0xff,0x21,  0x02,0x01,
  0x61,0x0f,0x08,

  /* codepoint 'F' RLE/nibble */
  0x41,0xff,0x21,  0x02,0x01,
  0x61,0x0f,0x00,

  /* codepoint 'G' RLE/4 */
  0x79,0xfe,0x01,0x41,0xc6,
  0x6d,0x07,0x08,0x08,0x07,

  /* codepoint 'H' RLE/nibble */
  0x51,0xff,0x20,  0x01,0xff,
  0x51,0x0f,0x00,  0x01,0x0f,

  /* codepoint 'I' plain bytes */
  0x01,0xff,0x01,
  0x08,0x0f,0x08,

  /* codepoint 'J' RLE/nibble */
  0x14,0x00,0x01,  0x11,0xff,0x01,
  0x41,0x07,0x08,  0x11,0x07,0x00,

  /* codepoint 'K' plain bytes */
  0xff,0x60,0x90,0x08,0x04,0x02,0x01,
  0x0f,0x00,0x00,0x01,0x02,0x04,0x08,

  /* codepoint 'L' RLE/nibble */
  0x61,0xff,0x00,
  0x61,0x0f,0x08,

  /* codepoint 'M' RLE/4 */
  0x95,0xff,0x02,0x0c,0x30,  0x15,0x0c,0x02,0xff,
  0x7d,0x0f,0x00,0x00,0x0f,

  /* codepoint 'N' plain bytes */
  0xff,0x08,0x10,0x20,0x40,0x80,0xff,
  0x0f,0x00,0x00,0x00,0x00,0x00,0x0f,

  /* codepoint 'O' RLE/nibble */
  0x51,0xfe,0x01,  0x01,0xfe,
  0x51,0x07,0x08,  0x01,0x07,

  /* codepoint 'P' RLE/nibble */
  0x51,0xff,0x41,  0x01,0x3e,
  0x61,0x0f,0x00,

  /* codepoint 'Q' RLE/4 */
  0x6d,0xfe,0x01,0x01,0xfe,
  0x59,0x07,0x08,0x0c,0x08,  0x05,0x18,0x27,

  /* codepoint 'R' plain bytes */
  0xff,0x41,0xc1,0x41,0x41,0x41,0x3e,
  0x0f,0x00,0x00,0x01,0x02,0x04,0x08,

  /* codepoint 'S' RLE/nibble */
  0x51,0x1e,0x21,  0x01,0xc6,
  0x51,0x06,0x08,  0x01,0x07,

  /* codepoint 'T' RLE/4 */
  0x37,0x01,0xff,0x01,
  0x37,0x00,0x0f,0x00,

  /* codepoint 'U' RLE/nibble */
  0x51,0xff,0x00,  0x01,0xff,
  0x51,0x07,0x08,  0x01,0x07,

  /* codepoint 'V' plain bytes */
  0x0f,0x70,0x80,0x00,0x80,0x70,0x0f,
  0x00,0x00,0x03,0x0c,0x03,0x00,0x00,

  /* codepoint 'W' plain bytes */
  0xff,0x00,0x00,0xc0,0xc0,0x00,0x00,0xff,
  0x0f,0x04,0x03,0x00,0x00,0x03,0x04,0x0f,

  /* codepoint 'X' plain bytes */
  0x03,0x0c,0x90,0x60,0x90,0x0c,0x03,
  0x0c,0x03,0x00,0x00,0x00,0x03,0x0c,

  /* codepoint 'Y' RLE/4 */
  0x55,0x03,0x0c,0x30,0xc0,  0x15,0x30,0x0c,0x03,
  0x37,0x00,0x0f,0x00,

  /* codepoint 'Z' RLE/4 */
  0x55,0x01,0x81,0x41,0x21,  0x15,0x11,0x09,0x07,
  0x3d,0x0f,0x08,0x08,

  /* codepoint '[' plain bytes */
  0xff,0x01,0x01,
  0x0f,0x08,0x08,

  /* codepoint ']' plain bytes */
  0x01,0x01,0xff,
  0x08,0x08,0x0f,

  /* codepoint '_' RLE/nibble */
  0x07,0x20,

  /* codepoint 'a' RLE/nibble */
  0x51,0x80,0x48,  0x01,0xf0,
  0x51,0x07,0x08,  0x01,0x0f,

  /* codepoint 'b' RLE/nibble */
  0x51,0xff,0x08,  0x01,0xf0,
  0x51,0x0f,0x08,  0x01,0x07,

  /* codepoint 'c' RLE/nibble */
  0x51,0xf0,0x08,  0x01,0x10,
  0x51,0x07,0x08,  0x01,0x04,

  /* codepoint 'd' RLE/nibble */
  0x51,0xf0,0x08,  0x01,0xff,
  0x51,0x07,0x08,  0x01,0x0f,

  /* codepoint 'e' RLE/nibble */
  0x51,0xf0,0x88,  0x01,0xf0,
  0x51,0x07,0x08,  0x01,0x04,

  /* codepoint 'f' RLE/4 */
  0x66,0x08,0xfe,0x09,0x01,
  0x36,0x00,0x0f,0x00,

  /* codepoint 'g' RLE/nibble */
  0x51,0xf0,0x08,  0x01,0xf8,
  0x51,0x07,0x48,  0x01,0x3f,

  /* codepoint 'h' RLE/nibble */
  0x51,0xff,0x08,  0x01,0xf0,
  0x51,0x0f,0x00,  0x01,0x0f,

  /* codepoint 'i' plain bytes */
  0x08,0xfb,0x00,
  0x08,0x0f,0x08,

  /* codepoint 'j' RLE/4 */
  0x17,0x00,0x08,0xfb,
  0x1d,0x30,0x40,0x3f,

  /* codepoint 'k' plain bytes */
  0xff,0x80,0x80,0x40,0x20,0x10,0x08,
  0x0f,0x00,0x00,0x01,0x02,0x04,0x08,

  /* codepoint 'l' plain bytes */
  0x01,0xff,0x00,
  0x08,0x0f,0x08,

  /* codepoint 'm' plain bytes */
  0xf8,0x08,0x08,0xf8,0x08,0x08,0xf0,
  0x0f,0x00,0x00,0x0f,0x00,0x00,0x0f,

  /* codepoint 'n' RLE/nibble */
  0x51,0xf8,0x08,  0x01,0xf0,
  0x51,0x0f,0x00,  0x01,0x0f,

  /* codepoint 'o' RLE/nibble */
  0x51,0xf0,0x08,  0x01,0xf0,
  0x51,0x07,0x08,  0x01,0x07,

  /* codepoint 'p' RLE/nibble */
  0x51,0xf8,0x08,  0x01,0xf0,
  0x51,0x7f,0x08,  0x01,0x07,

  /* codepoint 'q' RLE/nibble */
  0x51,0xf0,0x08,  0x01,0xf8,
  0x51,0x07,0x08,  0x01,0x7f,

  /* codepoint 'r' RLE/nibble */
  0x11,0xf8,0x20,  0x41,0x10,0x08,
  0x61,0x0f,0x00,

  /* codepoint 's' RLE/nibble */
  0x51,0x70,0x88,  0x01,0x10,
  0x51,0x04,0x08,  0x01,0x07,

  /* codepoint 't' RLE/4 */
  0x66,0x08,0xff,0x08,0x00,
  0x36,0x00,0x07,0x08,

  /* codepoint 'u' RLE/nibble */
  0x51,0xf8,0x00,  0x01,0xf8,
  0x51,0x07,0x08,  0x01,0x0f,

  /* codepoint 'v' plain bytes */
  0x38,0xc0,0x00,0x00,0x00,0xc0,0x38,
  0x00,0x00,0x03,0x0c,0x03,0x00,0x00,

  /* codepoint 'w' plain bytes */
  0xf8,0x00,0x00,0xc0,0x00,0x00,0xf8,
  0x07,0x08,0x08,0x0f,0x08,0x08,0x07,

  /* codepoint 'x' plain bytes */
  0x18,0x20,0x40,0x80,0x40,0x20,0x18,
  0x0c,0x02,0x01,0x00,0x01,0x02,0x0c,

  /* codepoint 'y' RLE/nibble */
  0x51,0xf8,0x00,  0x01,0xf8,
  0x51,0x07,0x48,  0x01,0x3f,

  /* codepoint 'z' plain bytes */
  0x08,0x08,0x08,0x88,0x48,0x28,0x18,
  0x0c,0x0a,0x09,0x08,0x08,0x08,0x08,
};

static const struct GlyphData PROGMEM _font_glyphs_terminus_18n[] = {
  {.codepoint = ' ',    .width=10, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '#',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width=10, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset=  14},
  {.codepoint = '.',    .width=10, .stripe_begin=1, .stripe_end=2, .left_margin=4, .right_margin=5, BDFONT_PLAIN(0), .data_offset=  16},
  {.codepoint = '/',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  17},
  {.codepoint = '0',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  29},
  {.codepoint = '1',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_RLE(2)  , .data_offset=  43},
  {.codepoint = '2',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  52},
  {.codepoint = '3',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset=  66},
  {.codepoint = '4',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset=  77},
  {.codepoint = '5',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset=  90},
  {.codepoint = '6',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 100},
  {.codepoint = '7',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 111},
  {.codepoint = '8',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 122},
  {.codepoint = '9',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 132},
  {.codepoint = ':',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=4, .right_margin=5, BDFONT_PLAIN(0), .data_offset= 143},
  {.codepoint = '<',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 145},
  {.codepoint = '>',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 157},
  {.codepoint = 'A',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 169},
  {.codepoint = 'B',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 179},
  {.codepoint = 'C',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 189},
  {.codepoint = 'D',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 199},
  {.codepoint = 'E',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 211},
  {.codepoint = 'F',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 219},
  {.codepoint = 'G',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 227},
  {.codepoint = 'H',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 237},
  {.codepoint = 'I',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 247},
  {.codepoint = 'J',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 253},
  {.codepoint = 'K',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 265},
  {.codepoint = 'L',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 279},
  {.codepoint = 'M',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 285},
  {.codepoint = 'N',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 299},
  {.codepoint = 'O',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 313},
  {.codepoint = 'P',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 323},
  {.codepoint = 'Q',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 331},
  {.codepoint = 'R',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 344},
  {.codepoint = 'S',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 358},
  {.codepoint = 'T',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 368},
  {.codepoint = 'U',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 376},
  {.codepoint = 'V',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 386},
  {.codepoint = 'W',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 400},
  {.codepoint = 'X',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 416},
  {.codepoint = 'Y',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 430},
  {.codepoint = 'Z',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 443},
  {.codepoint = '[',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 456},
  {.codepoint = ']',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 462},
  {.codepoint = '_',    .width=10, .stripe_begin=1, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 468},
  {.codepoint = 'a',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 470},
  {.codepoint = 'b',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 480},
  {.codepoint = 'c',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 490},
  {.codepoint = 'd',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 500},
  {.codepoint = 'e',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 510},
  {.codepoint = 'f',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 520},
  {.codepoint = 'g',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 529},
  {.codepoint = 'h',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 539},
  {.codepoint = 'i',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 549},
  {.codepoint = 'j',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_RLE(2)  , .data_offset= 555},
  {.codepoint = 'k',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 563},
  {.codepoint = 'l',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 577},
  {.codepoint = 'm',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 583},
  {.codepoint = 'n',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 597},
  {.codepoint = 'o',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 607},
  {.codepoint = 'p',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 617},
  {.codepoint = 'q',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 627},
  {.codepoint = 'r',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 637},
  {.codepoint = 's',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 646},
  {.codepoint = 't',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 656},
  {.codepoint = 'u',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 665},
  {.codepoint = 'v',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 675},
  {.codepoint = 'w',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 689},
  {.codepoint = 'x',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 703},
  {.codepoint = 'y',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 717},
  {.codepoint = 'z',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 727},
};

const struct FontData PROGMEM font_terminus_18n = {
  .available_glyphs = 73,
  .baseline = 12,
  .stripes = 2,
  .bits = _font_data_terminus_18n,
  .glyphs = _font_glyphs_terminus_18n
};
