/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-20n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--20-200-72-72-C-100-ISO10646-1
 *      Size: 20   Baseline at: 13
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */

#include "font-terminus_20n.h"

static const uint8_t PROGMEM _font_data_terminus_20n[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '#' plain bytes */
  0x10,0xff,0x10,0x10,0x10,0xff,0x10,
  0x01,0x1f,0x01,0x01,0x01,0x1f,0x01,

  /* codepoint '-' RLE/nibble */
  0x07,0x40,

  /* codepoint '.' plain bytes */
  0x18,

  /* codepoint '/' plain bytes */
  0x00,0x00,0x80,0x60,0x18,0x06,
  0x18,0x06,0x01,0x00,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xfe,0x01,0x81,0x41,0x21,0x11,0xfe,
  0x0f,0x11,0x10,0x10,0x10,0x10,0x0f,

  /* codepoint '1' RLE/4 */
  0x95,0x04,0x02,0xff,0x00,
  0x26,0x10,0x1f,0x10,

  /* codepoint '2' plain bytes */
  0x0e,0x01,0x01,0x01,0x81,0x41,0x3e,
  0x18,0x14,0x12,0x11,0x10,0x10,0x10,

  /* codepoint '3' RLE/nibble */
  0x11,0x06,0x01,  0x14,0x41,0xbe,
  0x51,0x0c,0x10,  0x01,0x0f,

  /* codepoint '4' plain bytes */
  0xc0,0x20,0x10,0x08,0x04,0x02,0xff,
  0x03,0x02,0x02,0x02,0x02,0x02,0x1f,

  /* codepoint '5' RLE/nibble */
  0x51,0x3f,0x21,  0x01,0xc1,
  0x51,0x0c,0x10,  0x01,0x0f,

  /* codepoint '6' RLE/nibble */
  0x11,0xfc,0x22,  0x14,0x21,0xc0,
  0x51,0x0f,0x10,  0x01,0x0f,

  /* codepoint '7' RLE/4 */
  0x5d,0x07,0x01,0xc1,0x31,  0x01,0x0f,
  0x37,0x00,0x1f,0x00,

  /* codepoint '8' RLE/nibble */
  0x51,0xbe,0x41,  0x01,0xbe,
  0x51,0x0f,0x10,  0x01,0x0f,

  /* codepoint '9' RLE/nibble */
  0x51,0x7e,0x81,  0x01,0xfe,
  0x41,0x00,0x10,  0x11,0x08,0x07,

  /* codepoint ':' plain bytes */
  0x30,
  0x0c,

  /* codepoint '<' plain bytes */
  0x40,0xa0,0x10,0x08,0x04,0x02,0x01,
  0x00,0x00,0x01,0x02,0x04,0x08,0x10,

  /* codepoint '>' plain bytes */
  0x01,0x02,0x04,0x08,0x10,0xa0,0x40,
  0x10,0x08,0x04,0x02,0x01,0x00,0x00,

  /* codepoint 'A' RLE/nibble */
  0x51,0xfe,0x41,  0x01,0xfe,
  0x51,0x1f,0x00,  0x01,0x1f,

  /* codepoint 'B' RLE/nibble */
  0x51,0xff,0x21,  0x01,0xde,
  0x51,0x1f,0x10,  0x01,0x0f,

  /* codepoint 'C' RLE/nibble */
  0x51,0xfe,0x01,  0x01,0x06,
  0x51,0x0f,0x10,  0x01,0x0c,

  /* codepoint 'D' RLE/nibble */
  0x41,0xff,0x01,  0x11,0x02,0xfc,
  0x41,0x1f,0x10,  0x11,0x08,0x07,

  /* codepoint 'E' RLE/nibble */
  0x41,0xff,0x41,  0x02,0x01,
  0x61,0x1f,0x10,

  /* codepoint 'F' RLE/nibble */
  0x41,0xff,0x41,  0x02,0x01,
  0x61,0x1f,0x00,

  /* codepoint 'G' RLE/4 */
  0x79,0xfe,0x01,0x41,0xc6,
  0x6d,0x0f,0x10,0x10,0x0f,

  /* codepoint 'H' RLE/nibble */
  0x51,0xff,0x40,  0x01,0xff,
  0x51,0x1f,0x00,  0x01,0x1f,

  /* codepoint 'I' plain bytes */
  0x01,0xff,0x01,
  0x10,0x1f,0x10,

  /* codepoint 'J' RLE/nibble */
  0x14,0x00,0x01,  0x11,0xff,0x01,
  0x41,0x0e,0x10,  0x11,0x0f,0x00,

  /* codepoint 'K' plain bytes */
  0xff,0x40,0xa0,0x10,0x08,0x04,0x03,
  0x1f,0x00,0x00,0x01,0x02,0x04,0x18,

  /* codepoint 'L' RLE/nibble */
  0x61,0xff,0x00,
  0x61,0x1f,0x10,

  /* codepoint 'M' RLE/4 */
  0x95,0xff,0x02,0x0c,0x30,  0x15,0x0c,0x02,0xff,
  0x7d,0x1f,0x00,0x00,0x1f,

  /* codepoint 'N' plain bytes */
  0xff,0x10,0x20,0x40,0x80,0x00,0xff,
  0x1f,0x00,0x00,0x00,0x00,0x01,0x1f,

  /* codepoint 'O' RLE/nibble */
  0x51,0xfe,0x01,  0x01,0xfe,
  0x51,0x0f,0x10,  0x01,0x0f,

  /* codepoint 'P' RLE/nibble */
  0x51,0xff,0x41,  0x01,0x3e,
  0x61,0x1f,0x00,

  /* codepoint 'Q' RLE/4 */
  0x6d,0xfe,0x01,0x01,0xfe,
  0x59,0x0f,0x10,0x18,0x10,  0x05,0x30,0x4f,

  /* codepoint 'R' plain bytes */
  0xff,0xc1,0x41,0x41,0x41,0x41,0x3e,
  0x1f,0x00,0x01,0x02,0x04,0x08,0x10,

  /* codepoint 'S' RLE/nibble */
  0x51,0x3e,0x41,  0x01,0x86,
  0x51,0x0c,0x10,  0x01,0x0f,

  /* codepoint 'T' RLE/4 */
  0x37,0x01,0xff,0x01,
  0x37,0x00,0x1f,0x00,

  /* codepoint 'U' RLE/nibble */
  0x51,0xff,0x00,  0x01,0xff,
  0x51,0x0f,0x10,  0x01,0x0f,

  /* codepoint 'V' plain bytes */
  0x0f,0xf0,0x00,0x00,0x00,0xf0,0x0f,
  0x00,0x00,0x07,0x18,0x07,0x00,0x00,

  /* codepoint 'W' plain bytes */
  0xff,0x00,0x00,0x80,0x80,0x00,0x00,0xff,
  0x1f,0x08,0x06,0x01,0x01,0x06,0x08,0x1f,

  /* codepoint 'X' plain bytes */
  0x03,0x0c,0xb0,0x40,0xb0,0x0c,0x03,
  0x18,0x06,0x01,0x00,0x01,0x06,0x18,

  /* codepoint 'Y' RLE/4 */
  0x55,0x03,0x0c,0x30,0xc0,  0x15,0x30,0x0c,0x03,
  0x37,0x00,0x1f,0x00,

  /* codepoint 'Z' RLE/4 */
  0x56,0x01,0x81,0x41,0x21,  0x05,0x11,0x0f,
  0xb5,0x1e,0x11,0x10,0x10,

  /* codepoint '[' plain bytes */
  0xff,0x01,0x01,
  0x1f,0x10,0x10,

  /* codepoint ']' plain bytes */
  0x01,0x01,0xff,
  0x10,0x10,0x1f,

  /* codepoint '_' RLE/nibble */
  0x07,0x40,

  /* codepoint 'a' RLE/nibble */
  0x51,0x00,0x90,  0x01,0xe0,
  0x51,0x0f,0x10,  0x01,0x1f,

  /* codepoint 'b' RLE/nibble */
  0x51,0xff,0x10,  0x01,0xe0,
  0x51,0x1f,0x10,  0x01,0x0f,

  /* codepoint 'c' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0x20,
  0x51,0x0f,0x10,  0x01,0x08,

  /* codepoint 'd' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0xff,
  0x51,0x0f,0x10,  0x01,0x1f,

  /* codepoint 'e' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0xe0,
  0x51,0x0f,0x11,  0x01,0x09,

  /* codepoint 'f' RLE/4 */
  0x66,0x10,0xfe,0x11,0x01,
  0x36,0x00,0x1f,0x00,

  /* codepoint 'g' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0xf0,
  0x51,0x0f,0x90,  0x01,0x7f,

  /* codepoint 'h' RLE/nibble */
  0x51,0xff,0x10,  0x01,0xe0,
  0x51,0x1f,0x00,  0x01,0x1f,

  /* codepoint 'i' plain bytes */
  0x10,0xf3,0x00,
  0x10,0x1f,0x10,

  /* codepoint 'j' RLE/4 */
  0x17,0x00,0x10,0xf3,
  0x1d,0x60,0x80,0x7f,

  /* codepoint 'k' plain bytes */
  0xff,0x00,0x00,0x80,0x40,0x20,0x10,
  0x1f,0x01,0x01,0x02,0x04,0x08,0x10,

  /* codepoint 'l' plain bytes */
  0x01,0xff,0x00,
  0x10,0x1f,0x10,

  /* codepoint 'm' plain bytes */
  0xf0,0x10,0x10,0xf0,0x10,0x10,0xe0,
  0x1f,0x00,0x00,0x1f,0x00,0x00,0x1f,

  /* codepoint 'n' RLE/nibble */
  0x51,0xf0,0x10,  0x01,0xe0,
  0x51,0x1f,0x00,  0x01,0x1f,

  /* codepoint 'o' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0xe0,
  0x51,0x0f,0x10,  0x01,0x0f,

  /* codepoint 'p' RLE/nibble */
  0x51,0xf0,0x10,  0x01,0xe0,
  0x51,0xff,0x10,  0x01,0x0f,

  /* codepoint 'q' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0xf0,
  0x51,0x0f,0x10,  0x01,0xff,

  /* codepoint 'r' RLE/nibble */
  0x11,0xf0,0x40,  0x41,0x20,0x10,
  0x61,0x1f,0x00,

  /* codepoint 's' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0x20,
  0x51,0x08,0x11,  0x01,0x0e,

  /* codepoint 't' RLE/4 */
  0x66,0x10,0xff,0x10,0x00,
  0x36,0x00,0x0f,0x10,

  /* codepoint 'u' RLE/nibble */
  0x51,0xf0,0x00,  0x01,0xf0,
  0x51,0x0f,0x10,  0x01,0x1f,

  /* codepoint 'v' plain bytes */
  0x70,0x80,0x00,0x00,0x00,0x80,0x70,
  0x00,0x01,0x06,0x18,0x06,0x01,0x00,

  /* codepoint 'w' plain bytes */
  0xf0,0x00,0x00,0x80,0x00,0x00,0xf0,
  0x0f,0x10,0x10,0x1f,0x10,0x10,0x0f,

  /* codepoint 'x' plain bytes */
  0x30,0x40,0x80,0x00,0x80,0x40,0x30,
  0x18,0x04,0x02,0x01,0x02,0x04,0x18,

  /* codepoint 'y' RLE/nibble */
  0x51,0xf0,0x00,  0x01,0xf0,
  0x51,0x0f,0x90,  0x01,0x7f,

  /* codepoint 'z' plain bytes */
  0x10,0x10,0x10,0x10,0x90,0x50,0x30,
  0x18,0x14,0x12,0x11,0x10,0x10,0x10,
};

static const struct GlyphData PROGMEM _font_glyphs_terminus_20n[] = {
  {.codepoint = ' ',    .width=10, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '#',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width=10, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset=  14},
  {.codepoint = '.',    .width=10, .stripe_begin=1, .stripe_end=2, .left_margin=4, .right_margin=5, BDFONT_PLAIN(0), .data_offset=  16},
  {.codepoint = '/',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  17},
  {.codepoint = '0',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  29},
  {.codepoint = '1',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_RLE(2)  , .data_offset=  43},
  {.codepoint = '2',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  52},
  {.codepoint = '3',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset=  66},
  {.codepoint = '4',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  77},
  {.codepoint = '5',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset=  91},
  {.codepoint = '6',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 101},
  {.codepoint = '7',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 112},
  {.codepoint = '8',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 123},
  {.codepoint = '9',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 133},
  {.codepoint = ':',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=4, .right_margin=5, BDFONT_PLAIN(0), .data_offset= 144},
  {.codepoint = '<',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 146},
  {.codepoint = '>',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 160},
  {.codepoint = 'A',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 174},
  {.codepoint = 'B',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 184},
  {.codepoint = 'C',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 194},
  {.codepoint = 'D',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 204},
  {.codepoint = 'E',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 216},
  {.codepoint = 'F',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 224},
  {.codepoint = 'G',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 232},
  {.codepoint = 'H',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 242},
  {.codepoint = 'I',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 252},
  {.codepoint = 'J',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 258},
  {.codepoint = 'K',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 270},
  {.codepoint = 'L',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 284},
  {.codepoint = 'M',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 290},
  {.codepoint = 'N',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 304},
  {.codepoint = 'O',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 318},
  {.codepoint = 'P',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 328},
  {.codepoint = 'Q',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 336},
  {.codepoint = 'R',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 349},
  {.codepoint = 'S',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 363},
  {.codepoint = 'T',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 373},
  {.codepoint = 'U',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 381},
  {.codepoint = 'V',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 391},
  {.codepoint = 'W',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 405},
  {.codepoint = 'X',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 421},
  {.codepoint = 'Y',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 435},
  {.codepoint = 'Z',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 448},
  {.codepoint = '[',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 461},
  {.codepoint = ']',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 467},
  {.codepoint = '_',    .width=10, .stripe_begin=1, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 473},
  {.codepoint = 'a',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 475},
  {.codepoint = 'b',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 485},
  {.codepoint = 'c',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 495},
  {.codepoint = 'd',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 505},
  {.codepoint = 'e',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 515},
  {.codepoint = 'f',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 525},
  {.codepoint = 'g',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 534},
  {.codepoint = 'h',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 544},
  {.codepoint = 'i',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 554},
  {.codepoint = 'j',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=3, BDFONT_RLE(2)  , .data_offset= 560},
  {.codepoint = 'k',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 568},
  {.codepoint = 'l',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_PLAIN(0), .data_offset= 582},
  {.codepoint = 'm',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 588},
  {.codepoint = 'n',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 602},
  {.codepoint = 'o',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 612},
  {.codepoint = 'p',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 622},
  {.codepoint = 'q',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 632},
  {.codepoint = 'r',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 642},
  {.codepoint = 's',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 651},
  {.codepoint = 't',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 661},
  {.codepoint = 'u',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 670},
  {.codepoint = 'v',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 680},
  {.codepoint = 'w',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 694},
  {.codepoint = 'x',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 708},
  {.codepoint = 'y',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 722},
  {.codepoint = 'z',    .width=10, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 732},
};

const struct FontData PROGMEM font_terminus_20n = {
  .available_glyphs = 73,
  .baseline = 13,
  .stripes = 2,
  .bits = _font_data_terminus_20n,
  .glyphs = _font_glyphs_terminus_20n
};
