/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-22n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--22-220-72-72-C-110-ISO10646-1
 *      Size: 22   Baseline at: 14
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */

#include "font-terminus_22n.h"

static const uint8_t PROGMEM _font_data_terminus_22n[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '#' RLE/4 */
  0x76,0x10,0xff,0x10,0xff,  0x02,0x10,
  0x76,0x02,0x3f,0x02,0x3f,  0x02,0x02,

  /* codepoint '-' RLE/nibble */
  0x08,0x80,

  /* codepoint '.' plain bytes */
  0x38,

  /* codepoint '/' plain bytes */
  0x00,0x00,0x00,0xc0,0x30,0x0c,0x03,
  0x30,0x0c,0x03,0x00,0x00,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xfc,0x02,0x01,0x81,0x41,0x21,0x12,0xfc,
  0x0f,0x12,0x21,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint '1' RLE/4 */
  0x55,0x08,0x04,0x02,0xff,  0x03,0x00,
  0x37,0x20,0x3f,0x20,

  /* codepoint '2' plain bytes */
  0x1c,0x02,0x01,0x01,0x01,0x81,0x42,0x3c,
  0x30,0x28,0x24,0x22,0x21,0x20,0x20,0x20,

  /* codepoint '3' plain bytes */
  0x04,0x02,0x41,0x41,0x41,0x41,0xa2,0x1c,
  0x08,0x10,0x20,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint '4' RLE/4 */
  0x55,0x80,0x40,0x20,0x10,  0x55,0x08,0x04,0x02,0xff,
  0x7d,0x07,0x04,0x04,0x3f,

  /* codepoint '5' RLE/nibble */
  0x51,0x3f,0x21,  0x11,0x41,0x81,
  0x11,0x0c,0x10,  0x14,0x20,0x10,  0x01,0x0f,

  /* codepoint '6' plain bytes */
  0xfc,0x22,0x21,0x21,0x21,0x21,0x41,0x80,
  0x0f,0x10,0x20,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint '7' RLE/4 */
  0x5d,0x07,0x01,0x01,0xc1,  0x05,0x31,0x0f,
  0xd7,0x00,0x3c,0x03,0x00,

  /* codepoint '8' plain bytes */
  0x1c,0xa2,0x41,0x41,0x41,0x41,0xa2,0x1c,
  0x0f,0x10,0x20,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint '9' plain bytes */
  0x7c,0x82,0x01,0x01,0x01,0x01,0x02,0xfc,
  0x00,0x20,0x21,0x21,0x21,0x21,0x11,0x0f,

  /* codepoint ':' plain bytes */
  0x38,
  0x1c,

  /* codepoint '<' plain bytes */
  0xc0,0x20,0x10,0x08,0x04,0x02,0x01,
  0x00,0x01,0x02,0x04,0x08,0x10,0x20,

  /* codepoint '>' plain bytes */
  0x01,0x02,0x04,0x08,0x10,0x20,0xc0,
  0x20,0x10,0x08,0x04,0x02,0x01,0x00,

  /* codepoint 'A' RLE/nibble */
  0x11,0xfc,0x82,  0x14,0x81,0x82,  0x01,0xfc,
  0x61,0x3f,0x00,  0x01,0x3f,

  /* codepoint 'B' RLE/nibble */
  0x51,0xff,0x41,  0x11,0xa2,0x1c,
  0x51,0x3f,0x20,  0x11,0x10,0x0f,

  /* codepoint 'C' plain bytes */
  0xfc,0x02,0x01,0x01,0x01,0x01,0x02,0x0c,
  0x0f,0x10,0x20,0x20,0x20,0x20,0x10,0x0c,

  /* codepoint 'D' RLE/nibble */
  0x51,0xff,0x01,  0x11,0x02,0xfc,
  0x51,0x3f,0x20,  0x11,0x10,0x0f,

  /* codepoint 'E' RLE/nibble */
  0x51,0xff,0x41,  0x02,0x01,
  0x71,0x3f,0x20,

  /* codepoint 'F' RLE/nibble */
  0x51,0xff,0x41,  0x02,0x01,
  0x71,0x3f,0x00,

  /* codepoint 'G' plain bytes */
  0xfc,0x02,0x01,0x01,0x81,0x81,0x82,0x8c,
  0x0f,0x10,0x20,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint 'H' RLE/nibble */
  0x61,0xff,0x40,  0x01,0xff,
  0x61,0x3f,0x00,  0x01,0x3f,

  /* codepoint 'I' RLE/4 */
  0x26,0x01,0xff,0x01,
  0x26,0x20,0x3f,0x20,

  /* codepoint 'J' RLE/nibble */
  0x24,0x00,0x01,  0x21,0xff,0x01,
  0x11,0x0e,0x10,  0x13,0x20,0x10,  0x21,0x0f,0x00,

  /* codepoint 'K' plain bytes */
  0xff,0xc0,0x20,0x10,0x08,0x04,0x02,0x01,
  0x3f,0x00,0x01,0x02,0x04,0x08,0x10,0x20,

  /* codepoint 'L' RLE/nibble */
  0x71,0xff,0x00,
  0x71,0x3f,0x20,

  /* codepoint 'M' plain bytes */
  0xff,0x02,0x0c,0x10,0x60,0x10,0x0c,0x02,0xff,
  0x3f,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x3f,

  /* codepoint 'N' plain bytes */
  0xff,0x10,0x20,0x40,0x80,0x00,0x00,0xff,
  0x3f,0x00,0x00,0x00,0x00,0x01,0x02,0x3f,

  /* codepoint 'O' plain bytes */
  0xfc,0x02,0x01,0x01,0x01,0x01,0x02,0xfc,
  0x0f,0x10,0x20,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint 'P' RLE/nibble */
  0x51,0xff,0x81,  0x11,0x42,0x3c,
  0x71,0x3f,0x00,

  /* codepoint 'Q' plain bytes */
  0xfc,0x02,0x01,0x01,0x01,0x01,0x02,0xfc,
  0x0f,0x10,0x20,0x28,0x30,0x20,0x50,0x8f,

  /* codepoint 'R' plain bytes */
  0xff,0x81,0x81,0x81,0x81,0x81,0x42,0x3c,
  0x3f,0x00,0x01,0x02,0x04,0x08,0x10,0x20,

  /* codepoint 'S' plain bytes */
  0x1c,0x22,0x41,0x41,0x41,0x41,0x82,0x04,
  0x08,0x10,0x20,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint 'T' RLE/nibble */
  0x14,0x01,0xff,  0x04,0x01,
  0x14,0x00,0x3f,  0x04,0x00,

  /* codepoint 'U' RLE/nibble */
  0x61,0xff,0x00,  0x01,0xff,
  0x11,0x0f,0x10,  0x14,0x20,0x10,  0x01,0x0f,

  /* codepoint 'V' plain bytes */
  0x1f,0xe0,0x00,0x00,0x00,0x00,0xe0,0x1f,
  0x00,0x01,0x0e,0x30,0x30,0x0e,0x01,0x00,

  /* codepoint 'W' plain bytes */
  0xff,0x00,0x00,0x00,0x80,0x00,0x00,0x00,0xff,
  0x3f,0x10,0x0c,0x02,0x01,0x02,0x0c,0x10,0x3f,

  /* codepoint 'X' plain bytes */
  0x03,0x0c,0x30,0xc0,0xc0,0x30,0x0c,0x03,
  0x30,0x0c,0x03,0x00,0x00,0x03,0x0c,0x30,

  /* codepoint 'Y' plain bytes */
  0x03,0x0c,0x30,0xc0,0x00,0xc0,0x30,0x0c,0x03,
  0x00,0x00,0x00,0x00,0x3f,0x00,0x00,0x00,0x00,

  /* codepoint 'Z' RLE/nibble */
  0x13,0x01,0x81,  0x11,0x41,0x21,  0x11,0x11,0x0f,
  0x11,0x3c,0x22,  0x51,0x21,0x20,

  /* codepoint '[' RLE/nibble */
  0x31,0xff,0x01,
  0x31,0x3f,0x20,

  /* codepoint ']' RLE/nibble */
  0x13,0x01,0xff,
  0x13,0x20,0x3f,

  /* codepoint '_' RLE/nibble */
  0x08,0x80,

  /* codepoint 'a' RLE/nibble */
  0x51,0x00,0x10,  0x11,0x20,0xc0,
  0x61,0x1e,0x21,  0x01,0x3f,

  /* codepoint 'b' RLE/nibble */
  0x51,0xff,0x10,  0x11,0x20,0xc0,
  0x51,0x3f,0x20,  0x11,0x10,0x0f,

  /* codepoint 'c' plain bytes */
  0xc0,0x20,0x10,0x10,0x10,0x10,0x20,0x40,
  0x0f,0x10,0x20,0x20,0x20,0x20,0x10,0x08,

  /* codepoint 'd' RLE/nibble */
  0x11,0xc0,0x20,  0x15,0x10,0xff,
  0x11,0x0f,0x10,  0x15,0x20,0x3f,

  /* codepoint 'e' RLE/nibble */
  0x11,0xc0,0x20,  0x14,0x10,0x20,  0x01,0xc0,
  0x11,0x0f,0x11,  0x15,0x21,0x11,

  /* codepoint 'f' RLE/4 */
  0x77,0x10,0xfe,0x11,0x01,
  0x77,0x00,0x3f,0x00,0x00,

  /* codepoint 'g' RLE/nibble */
  0x11,0xc0,0x20,  0x15,0x10,0xf0,
  0x11,0x0f,0x10,  0x15,0x20,0xff,
  0x51,0x00,0x02,  0x11,0x01,0x00,

  /* codepoint 'h' RLE/nibble */
  0x51,0xff,0x10,  0x11,0x20,0xc0,
  0x61,0x3f,0x00,  0x01,0x3f,

  /* codepoint 'i' RLE/4 */
  0x26,0x10,0xf7,0x00,
  0x26,0x20,0x3f,0x20,

  /* codepoint 'j' RLE/4 */
  0x1b,0x00,0x10,0xf7,
  0x5d,0xc0,0x00,0x00,0xff,
  0x5d,0x01,0x02,0x02,0x01,

  /* codepoint 'k' plain bytes */
  0xff,0x00,0x00,0x80,0x40,0x20,0x10,
  0x3f,0x03,0x03,0x04,0x08,0x10,0x20,

  /* codepoint 'l' RLE/4 */
  0x26,0x01,0xff,0x00,
  0x26,0x20,0x3f,0x20,

  /* codepoint 'm' RLE/4 */
  0x9d,0xf0,0x10,0xf0,0x10,  0x05,0x20,0xc0,
  0xdd,0x3f,0x00,0x3f,0x00,  0x01,0x3f,

  /* codepoint 'n' RLE/nibble */
  0x51,0xf0,0x10,  0x11,0x20,0xc0,
  0x61,0x3f,0x00,  0x01,0x3f,

  /* codepoint 'o' plain bytes */
  0xc0,0x20,0x10,0x10,0x10,0x10,0x20,0xc0,
  0x0f,0x10,0x20,0x20,0x20,0x20,0x10,0x0f,

  /* codepoint 'p' RLE/nibble */
  0x51,0xf0,0x10,  0x11,0x20,0xc0,
  0x51,0xff,0x20,  0x11,0x10,0x0f,
  0x71,0x03,0x00,

  /* codepoint 'q' RLE/nibble */
  0x11,0xc0,0x20,  0x15,0x10,0xf0,
  0x11,0x0f,0x10,  0x15,0x20,0xff,
  0x17,0x00,0x03,

  /* codepoint 'r' RLE/nibble */
  0x11,0xf0,0x40,  0x51,0x20,0x10,
  0x71,0x3f,0x00,

  /* codepoint 's' RLE/nibble */
  0x61,0xe0,0x10,  0x01,0x20,
  0x61,0x10,0x21,  0x01,0x1e,

  /* codepoint 't' RLE/4 */
  0x77,0x10,0xff,0x10,0x00,
  0x77,0x00,0x1f,0x20,0x20,

  /* codepoint 'u' RLE/nibble */
  0x61,0xf0,0x00,  0x01,0xf0,
  0x11,0x0f,0x10,  0x15,0x20,0x3f,

  /* codepoint 'v' plain bytes */
  0x70,0x80,0x00,0x00,0x00,0x00,0x80,0x70,
  0x00,0x03,0x0c,0x30,0x30,0x0c,0x03,0x00,

  /* codepoint 'w' RLE/4 */
  0xdd,0xf0,0x00,0x80,0x00,  0x01,0xf0,
  0xdd,0x1f,0x20,0x3f,0x20,  0x01,0x1f,

  /* codepoint 'x' plain bytes */
  0x30,0x40,0x80,0x00,0x00,0x80,0x40,0x30,
  0x30,0x08,0x04,0x03,0x03,0x04,0x08,0x30,

  /* codepoint 'y' RLE/nibble */
  0x61,0xf0,0x00,  0x01,0xf0,
  0x11,0x0f,0x10,  0x15,0x20,0xff,
  0x51,0x00,0x02,  0x11,0x01,0x00,

  /* codepoint 'z' RLE/nibble */
  0x15,0x10,0x90,  0x11,0x50,0x30,
  0x11,0x30,0x28,  0x11,0x24,0x22,  0x31,0x21,0x20,
};

static const struct GlyphData PROGMEM _font_glyphs_terminus_22n[] = {
  {.codepoint = ' ',    .width=11, .stripe_begin=2, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '#',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=   0},
  {.codepoint = '-',    .width=11, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset=  14},
  {.codepoint = '.',    .width=11, .stripe_begin=1, .stripe_end=2, .left_margin=5, .right_margin=5, BDFONT_PLAIN(0), .data_offset=  16},
  {.codepoint = '/',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  17},
  {.codepoint = '0',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  31},
  {.codepoint = '1',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset=  47},
  {.codepoint = '2',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  58},
  {.codepoint = '3',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset=  74},
  {.codepoint = '4',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset=  90},
  {.codepoint = '5',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 105},
  {.codepoint = '6',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 119},
  {.codepoint = '7',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 135},
  {.codepoint = '8',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 148},
  {.codepoint = '9',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 164},
  {.codepoint = ':',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=5, .right_margin=5, BDFONT_PLAIN(0), .data_offset= 180},
  {.codepoint = '<',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 182},
  {.codepoint = '>',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 196},
  {.codepoint = 'A',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 210},
  {.codepoint = 'B',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 223},
  {.codepoint = 'C',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 235},
  {.codepoint = 'D',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 251},
  {.codepoint = 'E',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 263},
  {.codepoint = 'F',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 271},
  {.codepoint = 'G',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 279},
  {.codepoint = 'H',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 295},
  {.codepoint = 'I',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_RLE(2)  , .data_offset= 305},
  {.codepoint = 'J',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 313},
  {.codepoint = 'K',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 328},
  {.codepoint = 'L',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 344},
  {.codepoint = 'M',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 350},
  {.codepoint = 'N',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 368},
  {.codepoint = 'O',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 384},
  {.codepoint = 'P',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 400},
  {.codepoint = 'Q',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 409},
  {.codepoint = 'R',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 425},
  {.codepoint = 'S',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 441},
  {.codepoint = 'T',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 457},
  {.codepoint = 'U',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 467},
  {.codepoint = 'V',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 480},
  {.codepoint = 'W',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 496},
  {.codepoint = 'X',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 514},
  {.codepoint = 'Y',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 530},
  {.codepoint = 'Z',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 548},
  {.codepoint = '[',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_RLE(1)  , .data_offset= 563},
  {.codepoint = ']',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=4, BDFONT_RLE(1)  , .data_offset= 569},
  {.codepoint = '_',    .width=11, .stripe_begin=1, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 575},
  {.codepoint = 'a',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 577},
  {.codepoint = 'b',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 588},
  {.codepoint = 'c',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 600},
  {.codepoint = 'd',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 616},
  {.codepoint = 'e',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 628},
  {.codepoint = 'f',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 642},
  {.codepoint = 'g',    .width=11, .stripe_begin=0, .stripe_end=3, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 652},
  {.codepoint = 'h',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 670},
  {.codepoint = 'i',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_RLE(2)  , .data_offset= 681},
  {.codepoint = 'j',    .width=11, .stripe_begin=0, .stripe_end=3, .left_margin=2, .right_margin=3, BDFONT_RLE(2)  , .data_offset= 689},
  {.codepoint = 'k',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 703},
  {.codepoint = 'l',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=3, .right_margin=3, BDFONT_RLE(2)  , .data_offset= 717},
  {.codepoint = 'm',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 725},
  {.codepoint = 'n',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 740},
  {.codepoint = 'o',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 751},
  {.codepoint = 'p',    .width=11, .stripe_begin=0, .stripe_end=3, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 767},
  {.codepoint = 'q',    .width=11, .stripe_begin=0, .stripe_end=3, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 782},
  {.codepoint = 'r',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 797},
  {.codepoint = 's',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 806},
  {.codepoint = 't',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 816},
  {.codepoint = 'u',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 826},
  {.codepoint = 'v',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 837},
  {.codepoint = 'w',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 853},
  {.codepoint = 'x',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 867},
  {.codepoint = 'y',    .width=11, .stripe_begin=0, .stripe_end=3, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 883},
  {.codepoint = 'z',    .width=11, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=2, BDFONT_RLE(1)  , .data_offset= 900},
};

const struct FontData PROGMEM font_terminus_22n = {
  .available_glyphs = 73,
  .baseline = 14,
  .stripes = 3,
  .bits = _font_data_terminus_22n,
  .glyphs = _font_glyphs_terminus_22n
};
