/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-20n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--20-200-72-72-C-100-ISO10646-1
 *      Size: 20   Baseline at: 13
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_20n_
#define FONT_terminus_20n_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_20n;

#endif /* FONT_terminus_20n_ */
