/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: terminus-24n.bdf
 *      Font: -xos4-Terminus-Medium-R-Normal--24-240-72-72-C-120-ISO10646-1
 *      Size: 24   Baseline at: 15
 * For chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:<>[]/-_# ]
 */
#ifndef FONT_terminus_24n_
#define FONT_terminus_24n_

#include "bdfont-support.h"

/* font containing 73 characters */
extern const struct FontData PROGMEM font_terminus_24n;

#endif /* FONT_terminus_24n_ */
